/* ============================================================
   MODULE 5 QUESTION BANK — Risk & Fraud
   20 Questions
   ============================================================ */
window.QB_M5 = [
  {q:"What is the primary difference between card skimming and card shimming?", options:["Skimming copies EMV chips, shimming copies magnetic stripes","Skimming uses physical overlays to read magnetic stripes; shimming uses ultra-thin inserts to read EMV chips","Skimming occurs online, shimming occurs in person","Skimming is committed by consumers, shimming by merchants"], answer:1, explanation:"Card skimming involves physical overlays placed on card slots to copy magnetic stripe data. Card shimming uses ultra-thin paper-like inserts inside EMV chip readers to intercept data from the chip during transaction processing."},
  {q:"Authorized Push Payment (APP) fraud occurs when:", options:["A fraudster pulls funds from a victim's account using stolen credentials","A victim is tricked (via phishing, BEC, or social engineering) into actively authorizing a credit push payment to a fraudster","An issuer incorrectly authorizes a transaction due to a ledger error","A merchant processes a chargeback without authorization"], answer:1, explanation:"APP fraud occurs when the victim themselves is deceived into authorizing a payment (e.g. wire, Zelle, RTP) to a scammer. Because the transfer is authorized by the account owner, standard fraud rules often do not cover recovery, making APP fraud difficult to resolve."},
  {q:"Under Nacha rules, what is the maximum unauthorized debit return rate threshold before an ODFI may face investigation or fines?", options:["0.1%","0.5%","1.0%","3.0%"], answer:1, explanation:"Nacha sets a strict unauthorized return rate threshold of 0.5% for debits. If an originator's unauthorized returns exceed this level, Nacha may investigate the ODFI, impose fines, or restrict origination."},
  {q:"Under Nacha rules, what is the administrative return rate threshold (for returns like account closed or no account)?", options:["0.5%","1.0%","3.0%","5.0%"], answer:2, explanation:"Nacha's administrative return rate threshold (covering return codes like R02 Account Closed and R03 No Account) is 3.0%."},
  {q:"Which ACH return code is used when a corporate receiver claims a CCD or CTX debit transaction was unauthorized?", options:["R07","R10","R16","R29"], answer:3, explanation:"Return code R29 (Corporate Customer Advises Not Authorized) is the business-to-business equivalent of R10. Businesses have a shorter return window (typically 2 banking days) compared to consumers (60 days)."},
  {q:"What does return code R16 signify?", options:["Insufficient funds","Account closed","Account frozen due to regulatory, OFAC, or court order","Invalid routing transit number"], answer:2, explanation:"R16 (Account Frozen) indicates that the RDFI has blocked access to the account, often due to a legal order, regulatory sanction, or OFAC match."},
  {q:"Under the EMV liability shift rules, who is liable for in-person counterfeit card fraud?", options:["The cardholder","The card network","The party (merchant or issuer) that has NOT upgraded their infrastructure to support EMV chip transactions","The acquiring bank in all cases"], answer:2, explanation:"The EMV liability shift dictates that if counterfeit fraud occurs at an in-person terminal, the liability shifts to whichever party (merchant or issuer) failed to support EMV chips. If the merchant did not have a chip reader, they absorb the fraud; if the issuer did not issue a chip card, the issuer absorbs it."},
  {q:"How does 3D Secure (3DS) shift transaction fraud liability for online card-not-present (CNP) transactions?", options:["It shifts liability from the merchant to the card issuer if the cardholder is successfully authenticated or the issuer doesn't support 3DS","It shifts liability from the issuer to the network","It makes the cardholder liable for all online fraud","It eliminates liability entirely for both parties"], answer:0, explanation:"3D Secure provides a liability shift for online merchants: if the transaction is authenticated via 3DS (or if the merchant attempted 3DS but the issuer's bank did not support it), liability for subsequent counterfeit/unauthorized fraud shifts to the card issuer."},
  {q:"In the context of credit card fraud, what is 'Friendly Fraud' (also known as first-party fraud)?", options:["A fraudster sharing stolen cards with friends","A legitimate cardholder making a purchase and then falsely claiming it was unauthorized to get a refund","A merchant charging a customer twice by mistake","A bank employee reversing a fee for a customer"], answer:1, explanation:"Friendly fraud occurs when a consumer makes a legitimate purchase and then disputes it as unauthorized, seeking to exploit consumer protection rules (like chargebacks) to keep the goods without paying."},
  {q:"Which technology is increasingly used by next-gen risk platforms to map relationships between bank accounts, IPs, and phone numbers to detect fraud rings?", options:["Relational SQL databases only","Graph Neural Networks (GNNs)","Static decision trees","Blockchain ledgers"], answer:1, explanation:"Graph Neural Networks (GNNs) are highly effective in fraud detection because they analyze the relationships (edges) between different entities (nodes like accounts, device IDs, phone numbers, locations) to identify complex fraud rings and money laundering patterns."},
  {q:"What is the timeframe for an RDFI to return a standard ACH debit return for Insufficient Funds (R01)?", options:["Within 24 hours","By the second banking day following the settlement date","60 calendar days","Indefinitely"], answer:1, explanation:"Under Nacha rules, standard administrative and financial returns (such as R01 NSF, R02 closed, R03 no account) must be returned by the RDFI such that the ODFI receives it by the opening of business on the second banking day following settlement."},
  {q:"What is the extended return window for a consumer seeking to return an unauthorized ACH debit (R10)?", options:["2 banking days","10 business days","60 calendar days from the settlement date","1 year"], answer:2, explanation:"To protect consumers, Regulation E and Nacha rules allow an extended return window of 60 calendar days from the transaction settlement date for unauthorized consumer ACH returns (R10, R05, R07)."},
  {q:"An ACH return code R08 means:", options:["Account closed","Payment stopped by receiver","No account / unable to locate","Credit entry refused"], answer:1, explanation:"R08 (Payment Stopped) indicates that the account owner has placed a stop-payment order on a specific debit transaction with their bank (similar to stopping a paper check)."},
  {q:"Why is generative AI considered a 'dual-use' risk in payments fraud?", options:["It can be used by both Visa and Mastercard","It enhances fraud detection systems but also enables fraudsters to automate highly convincing phishing, deepfake voice scams, and synthetic identities","It requires two separate systems to run","It only works on credit and debit cards"], answer:1, explanation:"Generative AI is a dual-use technology because while risk teams use it for synthetically training models, fraudsters exploit it to scale and automate highly convincing phishing emails, deepfake voice bank alerts, and fake documentation to bypass KYC."},
  {q:"What is the first phase of a card dispute/chargeback cycle?", options:["Arbitration","Retrieval Request","Chargeback / Dispute filing by the issuer","Pre-arbitration"], answer:2, explanation:"The dispute cycle begins when a cardholder disputes a charge, prompting the issuing bank to file a formal dispute/chargeback through the network against the acquirer/merchant."},
  {q:"In card disputes, what is the 'Arbitration' stage?", options:["A casual meeting between the merchant and consumer","The final network review where Visa or Mastercard makes a binding decision on the dispute, charging a heavy fee to the losing party","An automated system that refunds the issuer","The initial filing of the dispute"], answer:1, explanation:"Arbitration is the final escalation stage in the card dispute lifecycle. If the issuer and acquirer cannot resolve the dispute through re-presentments, the card network steps in to review the evidence and issue a binding decision, charging the losing bank several hundred dollars in fees."},
  {q:"Which of the following is a key measure used by risk teams to monitor transaction fraud rate thresholds?", options:["Total ledger balances","Basis points (bps) of fraud volume to total processing volume","The speed of the network router","The number of customer accounts created"], answer:1, explanation:"Risk teams typically measure fraud in basis points (bps), where 1 bp equals 0.01% of total transaction volume. Staying below industry thresholds (e.g. 5-10 bps) is critical to avoiding card network compliance programs."},
  {q:"What is 'Synthetic Identity Fraud'?", options:["Using a stolen credit card to buy artificial materials","Combining real data (such as a valid SSN) with fake data (fake name, DOB) to construct a completely new, artificial identity that doesn't belong to any real person","Using a pseudonym on an online account","Stealing a complete identity from a real person"], answer:1, explanation:"Synthetic identity fraud involves creating a new identity from a combination of real and fake credentials (e.g. using a real child's SSN with a fake name and date of birth). Because it is not a direct clone of an existing person, it is harder for traditional KYC systems to detect."},
  {q:"Which return code indicates that a consumer has revoked their standing authorization for a recurring payment (meaning the transaction was authorized initially, but the authorization was cancelled)?", options:["R01","R07","R10","R29"], answer:1, explanation:"R07 (Authorization Revoked by Customer) is used when the receiver originally authorized the originator to debit their account but subsequently cancelled/revoked that authority before the debit was processed."},
  {q:"What is the primary operational risk of real-time payments (RTP & FedNow) from a fraud perspective?", options:["Transactions can take several days to fail","The immediate and irrevocable finality of settlement leaves no window to freeze or recall funds once they leave the sending bank","The networks do not support security keys","Smaller banks are excluded from the networks"], answer:1, explanation:"Because RTP and FedNow settle with immediate finality in seconds, there is no clearing lag or overnight window to detect, recall, or reverse fraudulent transactions, necessitating highly sophisticated, real-time pre-funding fraud scoring."}
];
