/* ============================================================
   MODULE 1 QUESTION BANK — Foundation
   20 Questions
   ============================================================ */
window.QB_M1 = [
  {q:"What is the primary distinction between clearing and settlement?", options:["Clearing is the message routing, settlement is the money transfer","Clearing is instant, settlement is batched","Clearing is consumer-facing, settlement is interbank","Clearing is debit-based, settlement is credit-based"], answer:0, explanation:"Clearing is the exchange of transaction details and calculation of net obligations between banks, while settlement is the actual transfer of funds (typically on central bank ledgers) that satisfies those obligations."},
  {q:"Which of the following is an example of commercial bank money?", options:["Reserves held at the Federal Reserve","Your checking account balance at Chase Bank","Physical dollar bills in a vault","U.S. Treasury bills"], answer:1, explanation:"Commercial bank money represents liabilities of commercial banks to depositors (e.g. checking/savings accounts). Central bank money represents reserve balances held at the central bank or physical cash."},
  {q:"What is a 'double-entry' ledger?", options:["A ledger stored in two separate data centers for redundancy","A bookkeeping system where every debit must have a corresponding credit","A system where transactions are cleared twice before posting","A bank account that requires two signers for approvals"], answer:1, explanation:"Double-entry bookkeeping is the accounting standard where every transaction requires both a debit (reduction or increase depending on account type) and a matching credit, ensuring that assets always equal liabilities plus equity."},
  {q:"In a 'push' payment system, who controls the payment initiation?", options:["The receiver (payee)","The network operator","The sender (payer)","The receiving bank"], answer:2, explanation:"In a push payment, the sender initiates the transaction by instructing their bank to send funds. The sender controls authorization, minimizing unauthorized fraud."},
  {q:"In a 'pull' payment system, what credentials must the sender share?", options:["A single-use token only","Their account numbers or credentials so the payee can drag funds","Their mobile banking password","No credentials are shared"], answer:1, explanation:"In a pull payment (like ACH debits or card checkouts), the receiver initiates the request to pull funds. To allow this, the sender must share their account routing numbers or credit card details beforehand."},
  {q:"Which of the following is the generic term for the bank that initiates a transaction on behalf of a sender?", options:["Acquiring Bank","Originating Bank","Receiving Bank","Sponsor Bank"], answer:1, explanation:"The originating bank (ODFI in ACH, issuing bank in cards) is the financial institution that validates the sender's balance and forwards the transaction message into the clearing network."},
  {q:"In payment terminology, who is the 'Receiver'?", options:["The bank receiving the transaction","The consumer who initiates a push payment","The payee or merchant receiving the proceeds of the payment","The card network routing the payment"], answer:2, explanation:"The 'Receiver' is the final recipient of the payment (the payee or merchant) who collects the transaction proceeds."},
  {q:"What is Real-Time Gross Settlement (RTGS)?", options:["Accumulating transactions and settling them in one net file at end-of-day","Settling each individual transaction immediately and gross on a one-by-one basis","Settling payments in real-time but netting them every hour","A settlement method used only for small consumer payments"], answer:1, explanation:"RTGS is a settlement mechanism where transactions are settled individually and gross in real time as they occur, ensuring instant finality."},
  {q:"What is Deferred Net Settlement (DNS)?", options:["Settling transactions gross but delaying them by 24 hours","Accumulating transactions over a window, netting offsetting balances, and settling the net amount later","A system where consumers pay their bills after 30 days","Settlement of international wires only"], answer:1, explanation:"DNS is a settlement model where transactions accumulate in batches, are netted multilaterally, and the net obligations are settled at designated times (e.g. standard ACH)."},
  {q:"Which role in a payments network clears records, nets balances, and routes messages between banks?", options:["The Originator","The Operator (Clearinghouse / Router)","The Receiver","The Sponsor Bank"], answer:1, explanation:"The Operator (such as FedACH, EPN, or card networks) acts as the central switch that receives files from originating banks, clears the records, routes them to receiving banks, and calculates settlement positions."},
  {q:"Which component of the payment lifecycle evaluates ledger balances, credit lines, and credentials in real-time to approve a transaction?", options:["Transportation","Authorization","Clearing","Settlement"], answer:1, explanation:"Authorization is the real-time check of funds availability, credit limits, account status, and transaction risk by the payer's bank (the issuer) to approve or decline a payment."},
  {q:"Money in a database does not exist as floating physical tokens. How is value transfer represented?", options:["By physical reserve deliveries","By coordinated database edits (debits and credits) on ledgers","By transmitting encrypted graphics files of bills","By updating security keys on smart cards only"], answer:1, explanation:"In modern banking, value transfer is represented by database edits — updating records to decrease (debit) one balance and increase (credit) another across ledger databases."},
  {q:"Which of the following describes central bank money?", options:["Checking account deposits at commercial banks","Account balances held by banks at the Federal Reserve","Cash cards issued by retail businesses","Crypto stablecoins pegged to USD"], answer:1, explanation:"Central bank money includes central bank reserves (balances held by commercial banks on the balance sheet of the central bank) and physical currency. It represents ultimate risk-free settlement finality."},
  {q:"What is the primary risk associated with a 'pull' payment compared to a 'push' payment?", options:["It is too slow to process","It requires higher fees for the sender","The exposure of sensitive account credentials, leading to higher unauthorized fraud","It cannot be used for business transactions"], answer:2, explanation:"Because pull payments require the sender to share routing, account, or card numbers with the receiver, they carry higher risks of credential theft and unauthorized transactions compared to sender-controlled push payments."},
  {q:"In the payment lifecycle, when does the legal satisfaction of the debt between the originating and receiving institutions occur?", options:["Upon initiation","During transportation","Upon clearing","At settlement"], answer:3, explanation:"Settlement is the final step in the lifecycle that legally transfers funds between the institutions, resolving and satisfying all cleared payment obligations between them."},
  {q:"Why is central bank money considered to have zero credit and liquidity risk?", options:["It is guaranteed by private commercial insurers","It is backed by the full faith and credit of the central bank/sovereign government","It uses blockchain security","It can only be spent in small amounts"], answer:1, explanation:"Central bank money is a liability of the central bank (the sovereign monetary authority), which has the power to print currency, making it free from default (credit) or liquidity risk."},
  {q:"What is the generic term for the bank that receives a transaction message and updates the receiver's ledger?", options:["Acquiring Bank","Receiving Bank","Sponsor Bank","Clearinghouse"], answer:1, explanation:"The receiving bank (RDFI in ACH, acquiring bank in cards) is the financial institution that receives the payment instruction and credits the final recipient's account."},
  {q:"Under the generic roles, what is the 'Originator'?", options:["The bank that creates the payment network","The sender/payer who initiates the payment flow","The clearinghouse routing files","The merchant receiving the funds"], answer:1, explanation:"The Originator is the sender or payer (the entity that initiates the payment instruction and provides the funds)."},
  {q:"Which payment lifecycle stage ensures that bad actors cannot easily compromise the transaction, and manages disputes like chargebacks?", options:["Transportation","Authorization","Risk Management","Settlement"], answer:2, explanation:"Risk Management includes fraud prevention scoring, identity checks, and chargeback/dispute resolution mechanisms to protect the network's integrity."},
  {q:"What is the primary characteristic of Deferred Net Settlement (DNS) in terms of liquidity?", options:["It requires massive pre-funding for every single transaction","It is highly liquidity-efficient because only netted balances are transferred","It settles 24/7/365 within seconds","It requires physical delivery of banknotes"], answer:1, explanation:"Because DNS nets offsetting obligations between banks before settlement, it significantly reduces the amount of central bank reserves banks need to hold to settle their daily transaction volumes, conserving liquidity."}
];
