/* ============================================================
   MODULE 6 QUESTION BANK — Compliance & Regulation
   20 Questions
   ============================================================ */
window.QB_M6 = [
  {q:"Which federal regulation governs consumer electronic fund transfers (EFTs), including debit card disputes and ACH transfers?", options:["Regulation Z","Regulation J","Regulation E","Regulation CC"], answer:2, explanation:"Regulation E implements the Electronic Fund Transfer Act (EFTA) and establishes consumer protections, dispute rights, and liability limits for electronic fund transfers (debit cards, ACH, ATMs, P2P)."},
  {q:"Under Regulation E, what is the maximum consumer liability for unauthorized transactions if reported within 2 business days of learning of the loss?", options:["$0","$50","$500","Unlimited"], answer:1, explanation:"Under Reg E, consumer liability is capped at $50 if the consumer reports the unauthorized transaction or loss of card/credentials within 2 business days of learning about it."},
  {q:"If a consumer reports unauthorized transactions between 2 business days and 60 calendar days after their periodic statement is sent, what is their maximum liability under Regulation E?", options:["$50","$100","$500","Unlimited"], answer:2, explanation:"If the consumer fails to report the loss within 2 business days but does so within 60 calendar days of the periodic statement being sent, their liability is capped at $500."},
  {q:"What happens to consumer liability under Regulation E if the consumer does NOT report unauthorized transactions within 60 calendar days after the periodic statement containing the charges was sent?", options:["Liability remains capped at $50","Liability remains capped at $500","The consumer has unlimited liability for any unauthorized transactions occurring after the 60-day window","The card issuer must reimburse the full amount regardless"], answer:2, explanation:"If the consumer does not notify the bank within 60 calendar days after the statement was transmitted, they face unlimited liability for any unauthorized transfers that occur after that 60-day period (meaning they cannot recover any funds lost after that date)."},
  {q:"Under Regulation E, what is the standard timeframe for a financial institution to investigate and resolve a consumer dispute before they must provide provisional credit?", options:["2 business days","10 business days","45 calendar days","90 calendar days"], answer:1, explanation:"The financial institution has 10 business days (extended to 20 business days for new accounts) to investigate and resolve the dispute. If they need more time, they must provide provisional credit for the disputed amount and can then take up to 45 calendar days (or 90 days for POS/foreign transactions) to finish the investigation."},
  {q:"The Durbin Amendment (enacted under the Dodd-Frank Act) applies to debit card interchange fee caps. Which issuers are exempt from this cap?", options:["All issuers are capped","Issuers with total assets under $10 billion","Credit union issuers only","Prepaid card programs only"], answer:1, explanation:"The Durbin Amendment caps debit card interchange fees for banks with assets of $10 billion or more. Smaller community banks and credit unions (under $10B) are exempt, allowing them to earn higher interchange rates to support their business models."},
  {q:"What is the statutory debit card interchange fee cap formula set under the Durbin Amendment for capped issuers?", options:["1% of the transaction value","2.5% flat fee","21 cents + 0.05% of the transaction value + a 1-cent fraud prevention adjustment","50 cents flat fee"], answer:2, explanation:"The Durbin cap restricts debit interchange for covered issuers to 21 cents plus 0.05% of the transaction value, with an additional 1-cent fraud prevention adjustment if the issuer meets certain security requirements."},
  {q:"Besides capping fees, what routing mandate does the Durbin Amendment impose on all debit card issuers?", options:["All transactions must route through SWIFT","Issuers must support routing on at least two unaffiliated networks (e.g. Visa/Mastercard plus a domestic PIN debit network like Star, Pulse, or Nyce)","All transactions must route through FedNow","Debit cards can only have one routing network for security"], answer:1, explanation:"The Durbin Amendment mandates that issuers cannot restrict routing to a single network or two affiliated networks. They must provide at least two unaffiliated networks on the card, giving merchants a choice in how to route transactions (e.g. routing over a cheaper regional PIN network instead of Visa/Mastercard)."},
  {q:"Which federal agency is responsible for rulemaking and enforcement of consumer financial protection laws, including Regulation E and Section 1033?", options:["The OCC","The Federal Reserve System","The Consumer Financial Protection Bureau (CFPB)","The FDIC"], answer:2, explanation:"The CFPB has primary rulemaking and enforcement authority over major consumer protection regulations, including Regulation E (EFTA), Regulation Z (TILA), and the new Section 1033 rules."},
  {q:"The CFPB's Section 1033 rule targets 'Open Banking'. What is its primary goal?", options:["To mandate that all banks use blockchain tech","To require data providers (banks) to establish secure developer APIs allowing consumers to safely share their financial data with third-party apps, while phasing out credential sharing and screen scraping","To make all bank accounts public","To ban consumer data sharing"], answer:1, explanation:"Section 1033 of the Dodd-Frank Act requires banks to provide consumers (and authorized third-party fintechs) secure access to their financial data via developer APIs. A primary operational goal is phasing out risky screen-scraping methods that require consumers to share their login passwords with third parties."},
  {q:"Under the Bank Secrecy Act (BSA), banks must file a Currency Transaction Report (CTR) for physical cash transactions exceeding what threshold?", options:["$1,000","$5,000","$10,000","Any amount"], answer:2, explanation:"Under FinCEN rules, financial institutions must file a Currency Transaction Report (CTR) for any physical deposit, withdrawal, exchange, or transfer of cash that exceeds $10,000 in a single business day."},
  {q:"What is a Suspicious Activity Report (SAR) in payments compliance?", options:["A report filed to the police by a merchant","A confidential report filed by a financial institution to FinCEN when they suspect a transaction involves money laundering, terrorist financing, or other illegal activities","A public database of fraudulent cards","A document sent to the consumer to warn them of fraud"], answer:1, explanation:"A SAR is a confidential filing submitted by financial institutions to FinCEN to report suspicious, anomalous, or potentially illegal transactions. SAR filings are highly restricted; it is a federal crime for a bank to tip off a customer that a SAR has been filed on them."},
  {q:"Which Treasury department agency administers and enforces economic and trade sanctions based on US foreign policy goals, maintaining the Specially Designated Nationals (SDN) list?", options:["FinCEN","The Federal Reserve","The Office of Foreign Assets Control (OFAC)","The SEC"], answer:2, explanation:"OFAC (Office of Foreign Assets Control) is responsible for administering and enforcing economic sanctions. Financial institutions must screen transactions and account owners against OFAC's Specially Designated Nationals (SDN) list to block transactions involving sanctioned countries, entities, or individuals."},
  {q:"What does KYC stand for in financial compliance?", options:["Know Your Clearinghouse","Keep Your Cash","Know Your Customer","Keyed Yield Capital"], answer:2, explanation:"KYC (Know Your Customer) is the mandatory process of verifying the identity of customers opening accounts to prevent money laundering, tax evasion, and terrorist financing, as required under the USA PATRIOT Act."},
  {q:"Which regulation governs credit cards, billing statements, interest rate calculations, and implementation of the Truth in Lending Act (TILA)?", options:["Regulation E","Regulation Z","Regulation J","Regulation CC"], answer:1, explanation:"Regulation Z implements the Truth in Lending Act (TILA) and governs consumer credit disclosures, credit cards, billing errors, interest calculations, and rules established under the CARD Act of 2009."},
  {q:"The Credit Card Accountability Responsibility and Disclosure (CARD) Act of 2009 enacted which restriction?", options:["It capped credit card interest rates at 10%","It banned credit card rewards programs","It restricted retroactive interest rate hikes on existing balances and established rules on fee caps, billing timing, and marketing to young adults","It eliminated late fees entirely"], answer:2, explanation:"The CARD Act of 2009 introduced major protections for credit card holders, including restricting banks from raising interest rates on existing balances, requiring clear disclosures, capping over-limit fees, and setting restrictions on marketing to college students."},
  {q:"Under the CARD Act, credit card billing statements must be delivered to consumers at least how many days before the payment due date?", options:["10 days","14 days","21 days","30 days"], answer:2, explanation:"The CARD Act requires issuers to deliver billing statements to credit card holders at least 21 days before the payment due date to ensure consumers have adequate time to review charges and pay without incurring late fees."},
  {q:"Which of the following is considered 'Structuring' under AML rules?", options:["Building a secure bank vault","Designing an API layout","Breaking up a single cash transaction into multiple transactions under the $10,000 CTR filing threshold to evade BSA reporting requirements","Opening accounts at multiple banks"], answer:2, explanation:"Structuring (or 'smurfing') is the illegal act of breaking up a large cash transaction into multiple smaller transactions, each below the $10,000 threshold, specifically to avoid triggering a Currency Transaction Report (CTR)."},
  {q:"Fintech partners operating in a Banking-as-a-Service (BaaS) model must comply with bank compliance standards because:", options:["They are legally banks themselves","The bank's federal regulator examines the bank's third-party partnerships, and the bank is ultimately responsible for ensuring compliance across its entire middleware and fintech portfolio","The CFPB requires all apps to have bank charters","The card networks require it for all web apps"], answer:1, explanation:"In a BaaS setup, the fintech app operates under the sponsor bank's charter. Federal regulators (like the OCC or FDIC) hold the sponsor bank directly responsible for the actions of its partners, making strict oversight and audit alignment mandatory."},
  {q:"Which compliance program requires banks to verify a customer's physical address, date of birth, and tax identification number (SSN/EIN) before opening an account?", options:["The Transaction Monitoring Program","The Customer Identification Program (CIP)","The OFAC screening program","The Durbin compliance program"], answer:1, explanation:"Under the USA PATRIOT Act, banks must maintain a Customer Identification Program (CIP) as part of their broader KYC program, requiring them to collect and verify minimum identity details (name, DOB, address, SSN/TIN) for every new customer."}
];
