/* ============================================================
   MODULE 2 QUESTION BANK — ACH, RTP, FedNow, Wires
   100 Questions
   ============================================================ */
window.QB_M2 = [

  /* ── ACH HISTORY & BASICS (1-10) ── */
  {q:"What does ACH stand for?", options:["Automated Clearing House","Automated Credit Hub","American Clearing House","Automated Clearance Hub"], answer:0, explanation:"ACH stands for Automated Clearing House — the batch-based electronic payment network used for credit and debit transfers in the United States."},
  {q:"Which organization owns and governs the ACH Network?", options:["The Federal Reserve","Nacha (formerly NACHA)","The Clearing House (TCH)","CFPB"], answer:1, explanation:"Nacha (formerly the National Automated Clearinghouse Association) is the governing body that sets the rules, standards, and compliance requirements for the ACH Network."},
  {q:"In which decade was the ACH Network first established?", options:["1950s","1960s","1970s","1980s"], answer:2, explanation:"The ACH Network was established in the early 1970s. Nacha was founded in 1974, and the first ACH transactions began processing around that time."},
  {q:"Which two entities operate the ACH Network infrastructure in the United States?", options:["Visa and Mastercard","SWIFT and FedACH","FedACH and EPN (Electronic Payments Network)","CHIPS and Fedwire"], answer:2, explanation:"The two ACH operators are FedACH (operated by the Federal Reserve Banks) and EPN (Electronic Payments Network), operated by The Clearing House (TCH)."},
  {q:"Which federal regulation governs consumer ACH transactions?", options:["Regulation J","Regulation E (EFTA)","Regulation CC","Regulation Z"], answer:1, explanation:"Regulation E, implementing the Electronic Fund Transfer Act (EFTA), governs consumer electronic fund transfers including ACH debits and credits to consumer accounts."},
  {q:"What is the primary characteristic that distinguishes ACH from wire transfers?", options:["ACH is faster","ACH processes in batches; wires are settled individually in real time","ACH is only for international payments","ACH has no dollar limits"], answer:1, explanation:"ACH is a batch-processing system — transactions accumulate throughout the day and settle in windows. Wire transfers (Fedwire, CHIPS) are real-time gross settlement (RTGS), settling individually and immediately."},
  {q:"Which of the following is NOT an ACH transaction type?", options:["ACH Credit","ACH Debit","ACH Reversal","ACH Swap"], answer:3, explanation:"There is no 'ACH Swap' transaction type. ACH supports Credits (push), Debits (pull), and Reversals (correcting erroneous transactions within 5 banking days)."},
  {q:"What is the maximum dollar limit for a single Same-Day ACH transaction (post-2022 increase)?", options:["$25,000","$100,000","$1,000,000","Unlimited"], answer:2, explanation:"As of March 2022, the per-transaction limit for Same-Day ACH was raised to $1,000,000, making it suitable for a much broader range of business payments."},
  {q:"In which year did Same-Day ACH credits first become available?", options:["2010","2013","2016","2019"], answer:2, explanation:"Same-Day ACH for credits launched in September 2016. Same-Day ACH debits followed in September 2017."},
  {q:"Which of the following is an example of an ACH Credit transaction?", options:["Recurring mortgage payment pulled from checking account","Payroll direct deposit from employer to employee","NSF fee charged to a consumer account","ATM cash withdrawal"], answer:1, explanation:"Payroll direct deposit is an ACH Credit — the employer (originator) pushes funds into the employee's bank account. The employee's bank is the RDFI that receives the credit."},

  /* ── PARTICIPANTS & ROLES (11-18) ── */
  {q:"What does ODFI stand for in ACH terminology?", options:["Original Deposit Financial Institution","Originating Depository Financial Institution","Outbound Debit Financial Institution","Optional Direct Fund Institution"], answer:1, explanation:"ODFI stands for Originating Depository Financial Institution — the bank that originates and submits ACH entries into the network on behalf of its customers (originators)."},
  {q:"What does RDFI stand for?", options:["Registered Debit Financial Institution","Receiving Depository Financial Institution","Regional Direct Fund Institution","Regulated Deposit Fund Intermediary"], answer:1, explanation:"RDFI stands for Receiving Depository Financial Institution — the bank that receives ACH entries and posts them to the receiver's account."},
  {q:"In an ACH payroll direct deposit scenario, which party is the 'Originator'?", options:["The employee","The employee's bank","The employer","Nacha"], answer:2, explanation:"The employer is the Originator — the party that initiates the ACH transaction by providing payment instructions to its bank (the ODFI). The employer authorizes the bank to originate the payroll credits."},
  {q:"Which party in an ACH transaction has the responsibility of warranting that proper authorization was obtained from the receiver?", options:["The ACH Operator","The RDFI","The ODFI","Nacha"], answer:2, explanation:"The ODFI warrants to the ACH network that the originator has obtained proper authorization from the receiver. This is a key compliance responsibility — if the originator didn't have authorization, the ODFI bears liability."},
  {q:"What is the role of the ACH Operator in a transaction?", options:["To issue the payment card","To authenticate the receiver","To sort, process, and route ACH entries between ODFIs and RDFIs","To set interest rates on the underlying transactions"], answer:2, explanation:"The ACH Operator (FedACH or EPN) receives batches from ODFIs, sorts entries, and distributes them to the appropriate RDFIs. It is the central switching infrastructure of the ACH network."},
  {q:"Which Nacha rule requires ODFIs to conduct due diligence on their originators?", options:["Originator Due Diligence","Know Your Customer (KYC)","Origination Agreement Requirements","Third-Party Sender rule"], answer:0, explanation:"Nacha's Originator Due Diligence rules require ODFIs to perform appropriate vetting of originators before allowing them to originate ACH transactions, including reviewing their business type, return rates, and authorization practices."},
  {q:"A Third-Party Sender in ACH is best described as:", options:["A bank that processes ACH on behalf of the government","An intermediary company that originates ACH on behalf of other originators using an ODFI's agreement","The Federal Reserve acting as operator","A consumer who authorizes recurring payments"], answer:1, explanation:"A Third-Party Sender is an entity that has an agreement with an ODFI and uses that agreement to originate ACH entries on behalf of other originators. Payment processors like PayPal's ACH arm or payroll companies often function as Third-Party Senders."},
  {q:"What is the maximum unauthorized debit return rate threshold before Nacha may investigate an ODFI?", options:["0.5%","1%","2%","5%"], answer:0, explanation:"Nacha sets an unauthorized return rate threshold of 0.5%. If an ODFI's originators consistently exceed this, Nacha may investigate or take action. The overall administrative return rate threshold is 3%."},

  /* ── SEC CODES (19-33) ── */
  {q:"What does the SEC code 'PPD' stand for?", options:["Pre-authorized Payment and Deposit","Prearranged Payment and Deposit Entry","Personal Payment Direct","Priority Payment Deposit"], answer:1, explanation:"PPD stands for Prearranged Payment and Deposit Entry. It is used for consumer credit and debit transactions where the receiver has signed a written authorization, such as payroll direct deposit or recurring bill pay."},
  {q:"Which SEC code is used for business-to-business ACH transactions?", options:["PPD","WEB","CCD","TEL"], answer:2, explanation:"CCD (Corporate Credit or Debit) is the SEC code for business-to-business ACH transactions. It is used to move funds between companies, such as vendor payments or intercompany transfers."},
  {q:"A consumer authorizes a one-time ACH debit over the telephone. Which SEC code applies?", options:["PPD","WEB","TEL","IAT"], answer:2, explanation:"TEL (Telephone-Initiated Entry) is used when authorization for an ACH debit is obtained verbally over the telephone. It applies to one-time or sporadic debits only — not recurring."},
  {q:"Which SEC code is used for ACH debits authorized via the internet?", options:["WEB","PPD","CCD","ARC"], answer:0, explanation:"WEB (Internet-Initiated/Mobile Entry) is the SEC code for consumer ACH debit transactions authorized via the internet or a mobile device. Originators using WEB must perform annual security audits."},
  {q:"What does the SEC code 'IAT' stand for and when is it used?", options:["Internal Account Transfer — for intrabank transfers","International ACH Transaction — for entries involving financial agencies outside the US","Immediate ACH Transfer — for same-day processing","Institutional ACH Transfer — for government payments"], answer:1, explanation:"IAT stands for International ACH Transaction. It is used when a transaction involves a financial agency outside the United States, such as a payment to a foreign bank account. IAT entries have enhanced OFAC screening requirements."},
  {q:"The SEC code 'ARC' is used for which type of transaction?", options:["Automated Recurring Credit","Accounts Receivable Entry — converting paper checks received by mail","Authorized Remote Collection","ACH Reversal Code"], answer:1, explanation:"ARC (Accounts Receivable Entry) is used to convert paper checks received by mail or drop-box into ACH debits. The check serves as the source document; the MICR line data is used for the ACH entry."},
  {q:"Which SEC code allows merchants to convert point-of-sale checks into ACH transactions?", options:["BOC","POP","ARC","RCK"], answer:1, explanation:"POP (Point-of-Purchase Entry) is used to convert paper checks presented at the point of sale into ACH debits. The consumer's original check is returned void at the time of the transaction."},
  {q:"What is the SEC code 'BOC' used for?", options:["Back Office Conversion — converting checks to ACH at back-office instead of POS","Business-Originated Credit","Bank-Originated Collection","Balance Overdraft Charge"], answer:0, explanation:"BOC (Back Office Conversion) allows merchants to collect a signed authorization at POS and then convert checks to ACH in the back office. The check is scanned after the consumer leaves."},
  {q:"The SEC code 'RCK' is used for:", options:["Re-presented Check Entry — re-presenting NSF checks as ACH","Real-time Credit — for instant payments","Recurring CCD — for corporate recurring payments","Remote Check Capture"], answer:0, explanation:"RCK (Re-presented Check Entry) allows originators to re-present a returned NSF check as an ACH debit — up to two times after the initial return. Strict consumer authorization and notice requirements apply."},
  {q:"Which SEC code is used for payroll credits to consumer accounts in most payroll processing?", options:["CCD","PPD","CTX","WEB"], answer:1, explanation:"PPD (Prearranged Payment and Deposit Entry) is the standard SEC code for payroll direct deposit — a recurring ACH credit from an employer to a consumer's bank account based on a standing written authorization."},
  {q:"What does 'CTX' stand for and what makes it unique?", options:["Corporate Tax Exchange — for IRS payments","Corporate Trade Exchange — allows addenda records for EDI data","Cash Transfer Express — for same-day corporate payments","Customer Text Export — for formatted payment data"], answer:1, explanation:"CTX (Corporate Trade Exchange) is a CCD variant that supports multiple addenda records, allowing EDI (Electronic Data Interchange) remittance data to accompany the payment. Used in complex B2B environments where detailed payment information must accompany the funds."},
  {q:"A consumer calls a utility company to authorize a one-time payment from their bank account. What SEC code applies?", options:["PPD","WEB","TEL","CIE"], answer:2, explanation:"TEL is used for consumer ACH debits authorized by telephone. Since the authorization is verbal and one-time (not recurring from an existing relationship), TEL applies. PPD requires a written/signed authorization."},
  {q:"Which SEC code is used for non-profit contributions initiated by donors online?", options:["PPD","WEB","TEL","CCD"], answer:1, explanation:"WEB is used for ACH debits authorized via the internet, including online charitable contributions from consumers. It applies to any consumer debit where the authorization was obtained over the internet or mobile channel."},
  {q:"The 'ENR' SEC code is used for:", options:["Employer-Initiated Non-Recurring payments","Enrollment in federal government benefit programs","Electronic Non-Recurring transactions","Emergency Payroll Runs"], answer:1, explanation:"ENR (Automated Enrollment Entry) is used by financial institutions to enroll receivers in federal government direct deposit programs (e.g., Social Security, SSI). It is a specialized code sent to a government agency."},
  {q:"Which SEC code would a bank use to originate a direct deposit of Social Security benefits to a recipient's account?", options:["PPD","CCD","DNE","PPD or DNE"], answer:0, explanation:"PPD is used for government benefit direct deposits to consumer accounts, including Social Security payments. DNE (Death Notification Entry) is a separate code used to notify the government of a recipient's death."},

  /* ── RETURN CODES (34-45) ── */
  {q:"An ACH transaction returned with code R01 means:", options:["Invalid account number","Insufficient funds in the account","Account closed","No account / unable to locate account"], answer:1, explanation:"R01 — Insufficient Funds. The RDFI could not post the ACH debit because the receiver's account lacked sufficient available funds to cover the transaction amount."},
  {q:"Return code R02 indicates:", options:["Insufficient funds","Account closed","Invalid account number","Unauthorized transaction"], answer:1, explanation:"R02 — Account Closed. The receiving account existed but has since been closed by the account holder. The originator should stop sending transactions to that account and seek updated information."},
  {q:"Which return code indicates that the receiver claims they never authorized the ACH debit?", options:["R05","R07","R10","R29"], answer:1, explanation:"R07 — Authorization Revoked by Customer. This return code is used when the receiver has authorized the originator in the past but has since revoked that authorization and the debit was still processed."},
  {q:"Return code R10 means:", options:["Account closed","Customer advises originator not authorized","Invalid account / routing number","Corporate customer advises not authorized"], answer:1, explanation:"R10 — Customer Advises Originator Not Authorized. Used when the receiver states they never authorized the originator at all — the original authorization was never given. This is different from R07 (authorization revoked after it was given)."},
  {q:"An ACH entry is returned with R16. This means:", options:["Insufficient funds","Account frozen by OFAC","Account number structure not valid","Non-transaction account"], answer:1, explanation:"R16 — Account Frozen. The RDFI has frozen the account due to a legal action, regulatory requirement, or bank policy (often an OFAC or court order). The originator cannot process further transactions until the freeze is lifted."},
  {q:"What is the standard return timeframe for an RDFI to return most unauthorized ACH transactions?", options:["24 hours","2 banking days","60 calendar days","180 days"], answer:2, explanation:"For most unauthorized consumer ACH debit returns (R05, R07, R10, R29), the RDFI has 60 calendar days from the settlement date to return the transaction. This is the extended return window that protects consumers."},
  {q:"Return code R03 means:", options:["Insufficient funds","Account closed","No account / unable to locate account","Bank account number structure invalid"], answer:2, explanation:"R03 — No Account / Unable to Locate Account. The RDFI cannot find an account matching the account number and routing number provided in the ACH entry. Commonly caused by data entry errors."},
  {q:"Which return code is used when a non-consumer receiver claims they never authorized a CCD debit?", options:["R07","R10","R29","R05"], answer:2, explanation:"R29 — Corporate Customer Advises Not Authorized. This is the business equivalent of R10 — used when a non-consumer (corporate) receiver claims the CCD, CTX, or CIE debit was not authorized."},
  {q:"Return code R23 is used when:", options:["Account is frozen","The credit entry is refused by the receiver","The receiving account has insufficient funds","The RDFI is unable to process the entry"], answer:1, explanation:"R23 — Credit Entry Refused by Receiver. Used when a receiver refuses to accept a credit entry — for example, a company that does not want to receive an incoming ACH credit from a particular originator."},
  {q:"What does return code R08 indicate?", options:["Account closed","Payment stopped by receiver","Insufficient funds","Non-transaction account"], answer:1, explanation:"R08 — Payment Stopped. The receiver has placed a stop-payment order on this specific ACH debit with their bank (RDFI). Similar to stopping a check payment."},
  {q:"Which return code indicates that a company account cannot accept ACH debits (e.g., a money market account)?", options:["R09","R20","R21","R22"], answer:1, explanation:"R20 — Non-Transaction Account. The receiving account is not set up to receive ACH transactions (e.g., certain investment accounts, certificates of deposit, or accounts restricted from ACH debits under the account agreement)."},
  {q:"An ODFI submits an ACH file and the ACH Operator rejects the entire file. What category of return does the ODFI receive?", options:["Return Entry","Notification of Change (NOC)","Rejected File","Administrative Return"], answer:2, explanation:"When an ACH Operator rejects an entire file (typically for formatting errors, invalid batch headers, or failed authentication), the ODFI receives a file-level rejection notice — distinct from individual entry returns."},

  /* ── SETTLEMENT & PROCESSING WINDOWS (46-53) ── */
  {q:"How many Same-Day ACH processing windows are available per business day?", options:["One","Two","Three","Four"], answer:2, explanation:"There are three Same-Day ACH processing windows per business day: a morning window (10:30 AM ET cutoff, 1:00 PM settlement), an afternoon window (2:45 PM ET cutoff, 5:00 PM settlement), and an evening window added in 2021 (4:45 PM ET cutoff, next morning settlement for RDFIs)."},
  {q:"What is the settlement timing for a standard (non-same-day) ACH credit?", options:["Real-time settlement","Same business day","Next business day (T+1)","Two business days (T+2)"], answer:2, explanation:"Standard ACH credits settle on the next business day (T+1). The originator's ODFI submits the batch, the ACH operator routes entries, and the RDFI posts the credit to the receiver's account the following business day."},
  {q:"When does an ACH debit typically settle relative to the initiation date?", options:["Same day","Next day (T+1)","Two days (T+2)","Three days (T+3)"], answer:1, explanation:"Standard ACH debits settle one business day (T+1) after the effective entry date. The ODFI submits the file 1 day prior to the desired settlement date (2 days prior for some operators), and the RDFI receives funds on the settlement date."},
  {q:"What is a 'Notification of Change' (NOC) in the ACH system?", options:["A notice from NACHA of a rule violation","A non-dollar entry from an RDFI informing the ODFI that account information has changed","An alert about suspicious activity","A notification that an ACH file was rejected"], answer:1, explanation:"A Notification of Change (NOC) is a non-dollar entry sent by the RDFI back through the network to the ODFI, indicating that certain payment-related information has changed (e.g., account number updated, routing number changed). Originators must update their records within 6 banking days."},
  {q:"What is the purpose of a 'Prenote' in ACH?", options:["A test zero-dollar transaction sent before a live transaction to verify account validity","A notice sent to the receiver before debiting their account","A regulatory filing required by Nacha for new originators","A pre-notification to the ACH Operator about a large batch"], answer:0, explanation:"A Prenote is a zero-dollar test transaction submitted before the first live ACH entry to verify that the account number and routing number are valid. If the prenote returns, the originator can fix the information before sending real money."},
  {q:"Under Nacha rules, how long must ACH authorization records be retained by the originator?", options:["1 year","2 years","6 years","Indefinitely"], answer:1, explanation:"Nacha rules require originators to retain ACH authorization records for a minimum of 2 years from the date the authorization is terminated or revoked. This enables investigation of unauthorized return claims."},
  {q:"What is the 'effective entry date' in an ACH transaction?", options:["The date the file was submitted to the ACH Operator","The date the originator expects the transaction to post to the receiver's account","The date the RDFI confirms posting","The date the ODFI debits the originator's account"], answer:1, explanation:"The effective entry date is the date the originator intends the transaction to be posted to the receiver's account — the desired settlement date. The ODFI must submit the file 1-2 days before the effective entry date for standard processing."},
  {q:"Which of the following correctly describes ACH's settlement model?", options:["Real-Time Gross Settlement (RTGS) — each transaction settles immediately","Deferred Net Settlement (DNS) — transactions accumulate and net balances settle at designated times","Multilateral netting via CHIPS","Correspondent banking with nostro/vostro accounts"], answer:1, explanation:"ACH uses Deferred Net Settlement (DNS). Transactions accumulate in batches throughout the day, and at settlement windows, net balances (credits minus debits) between financial institutions settle through Fed Reserve accounts or bilateral balances."},

  /* ── ACH COMPLIANCE & FRAUD (54-60) ── */
  {q:"The Nacha WEB Debit rule requires originators using the WEB SEC code to:", options:["Obtain notarized authorization","Conduct annual audits of their internet security system","File quarterly reports with FinCEN","Get CFPB approval before originating"], answer:1, explanation:"Nacha's WEB Debit Account Validation rule requires originators using the WEB SEC code to (a) conduct annual audits of their internet security, and (b) validate that a consumer's bank account is legitimate before initiating the first debit — reducing fraud from fake account numbers."},
  {q:"Under Nacha rules, an originator whose unauthorized return rate exceeds 0.5% may face:", options:["Automatic shutdown of all ACH origination","Investigation by Nacha and potential sanctions against the ODFI","A $1,000 fine per returned transaction","Mandatory enrollment in fraud monitoring only"], answer:1, explanation:"Exceeding the 0.5% unauthorized ACH return rate threshold triggers a Nacha investigation. Nacha can impose fines on the ODFI, require remediation of the originator's practices, or restrict the originator's ability to originate ACH transactions."},
  {q:"What is 'ACH Kiting'?", options:["Using multiple ACH accounts to inflate float and withdraw funds before settlement","A legitimate float management technique","Using the same ACH transaction twice for accounting purposes","A term for ACH transactions that cross midnight"], answer:0, explanation:"ACH Kiting involves exploiting the timing gap between ACH initiation and settlement — moving money between accounts to create artificial balances. It's a form of fraud. Banks detect it through velocity monitoring and balance verification at the time of origination."},
  {q:"Which Nacha rule requires ODFIs to validate the account to which an ACH debit will be applied before the first debit?", options:["WEB Debit Account Validation Rule","ACH Pre-Validation Mandate","ODFI Originator Verification Standard","Prenote Requirement"], answer:0, explanation:"The Nacha WEB Debit Account Validation Rule (effective March 2022) requires originators using the WEB SEC code to perform account validation — confirming the bank account is real and belongs to the expected consumer — before the first WEB debit is submitted."},
  {q:"What is the primary risk management concern with Same-Day ACH compared to standard ACH?", options:["Higher transaction fees","Faster availability means less time to detect and stop fraudulent transactions before funds move","Same-Day ACH has more return codes","Same-Day ACH requires a signed authorization for every transaction"], answer:1, explanation:"The accelerated settlement of Same-Day ACH means fraud detection windows are compressed. Unlike standard ACH where fraud can sometimes be detected overnight before settlement, Same-Day ACH settles in hours — giving banks and originators less time to identify and block fraudulent transactions."},
  {q:"A payroll company accidentally submits duplicate payroll files. What is the proper remedy under Nacha rules?", options:["File a SAR with FinCEN","Submit a reversal entry within 5 banking days of the settlement date","Contact the RDFI directly and request a chargeback","There is no remedy — the receiver keeps duplicate payments"], answer:1, explanation:"Under Nacha rules, an ODFI/originator can reverse an erroneous or duplicate ACH entry by submitting a reversal (or reversing file) within 5 banking days of the settlement date of the original entry. Proper notification to affected receivers is required."},
  {q:"Which federal agency examines large nonbank payment processors for compliance with ACH rules?", options:["FDIC","OCC","CFPB","The Federal Reserve only"], answer:2, explanation:"The CFPB has supervisory authority over large nonbank entities that process a significant volume of consumer payments, including ACH. Traditional bank ODFIs are examined by their primary federal regulator (OCC, FDIC, or Fed)."},

  /* ── RTP (61-72) ── */
  {q:"RTP stands for:", options:["Real-Time Payment","Rapid Transfer Protocol","Real-Time Processing","Regulated Transfer Platform"], answer:0, explanation:"RTP stands for Real-Time Payments — the instant payment network launched by The Clearing House (TCH) in 2017. It enables 24/7/365 credit push payments that settle in seconds."},
  {q:"Which organization operates the RTP network in the United States?", options:["The Federal Reserve","Nacha","The Clearing House (TCH)","Visa"], answer:2, explanation:"The Clearing House (TCH) — a banking industry consortium owned by large US banks — launched and operates the RTP network. TCH is the oldest banking organization in the US, founded in 1853."},
  {q:"In what year did the RTP network launch?", options:["2015","2017","2019","2021"], answer:1, explanation:"The RTP network launched in November 2017, making it the first new payments rail built in the United States in over 40 years. The initial participants were major banks including JPMorgan Chase, BofA, and U.S. Bank."},
  {q:"What is the maximum transaction limit on the RTP network?", options:["$25,000","$100,000","$1,000,000","$10,000,000"], answer:3, explanation:"As of February 2025, the RTP network supports transactions up to $10,000,000 per payment. The limit was raised from $1,000,000 to $10,000,000 to enable broader high-value B2B use cases."},
  {q:"What messaging standard does the RTP network use?", options:["ISO 8583","SWIFT MT","ISO 20022","ANSI X12"], answer:2, explanation:"The RTP network uses ISO 20022 — a modern, rich data messaging standard that supports extensive remittance information, structured data, and machine-readable content. This is superior to ACH's legacy formats for data richness."},
  {q:"Which of the following is a unique capability of RTP that ACH does not have?", options:["Lower transaction fees","Request for Payment (RFP) message type","International reach","Bulk file processing"], answer:1, explanation:"RTP supports a Request for Payment (RFP) message — a non-binding request sent from payee to payer through the network, asking for a payment. The payer can approve and pay, creating a complete end-to-end electronic payment request and fulfillment workflow."},
  {q:"What does 'Real-Time Gross Settlement' (RTGS) mean in the context of RTP?", options:["Transactions accumulate in batches and net-settle at intervals","Each individual payment settles immediately and irrevocably, one at a time","Transactions settle at end of business day","Multiple transactions between two banks are netted before settlement"], answer:1, explanation:"RTGS means each payment settles individually and in real time, not as part of a batch. On the RTP network, funds move from the paying institution to the receiving institution within seconds, with immediate finality."},
  {q:"What happens to RTP transaction funds at the TCH level?", options:["TCH holds all funds in a central account for 24 hours","Each participating bank pre-funds a TCH account; RTP payments debit and credit these accounts in real time","Funds settle via Fedwire at end of day","TCH borrows from the Fed for intraday liquidity"], answer:1, explanation:"RTP uses a pre-funded model — participating banks maintain accounts at The Clearing House, funded via Fedwire. When an RTP payment is initiated, TCH debits the sending bank's prefunded account and credits the receiving bank's account in real time."},
  {q:"The RFP (Request for Payment) in the RTP network is best described as:", options:["A legally binding payment obligation","A non-binding request for payment that the payer can accept, decline, or ignore","An automated recurring debit authorization","A dispute message sent after a failed payment"], answer:1, explanation:"The RFP is a non-binding message — it is a request, not an instruction. The payer receives the RFP through their bank's app and chooses whether to pay. If approved, the payer initiates a credit push payment. Neither the RFP nor the payment can be reversed once sent."},
  {q:"Which of the following industries is RTP's Request for Payment (RFP) most commonly used in?", options:["International trade finance","Consumer P2P payments","B2B invoice payments and mortgage collections","Government benefits disbursement"], answer:2, explanation:"RFP has seen strong adoption in B2B invoice payment workflows and mortgage/loan servicing — lenders send RFPs to borrowers for monthly payments, reducing missed payments and eliminating manual check processes."},
  {q:"RTP payments are described as 'irrevocable.' What does this mean practically?", options:["The sender can request a return within 24 hours","Once posted, the receiving bank cannot be forced to return the funds — only a voluntary return is possible","The payment can be reversed by the network for fraud","Irrevocability only applies to amounts over $10,000"], answer:1, explanation:"RTP payment irrevocability means the payment is final upon settlement. Unlike ACH (which has return codes and reversal windows), there is no network-mandated return mechanism for RTP. If the payer sent money by mistake, they must contact the receiver and request a voluntary return."},
  {q:"Which of the following best explains why not all small banks and credit unions are on the RTP network?", options:["Small banks are prohibited from joining","RTP requires participants to have pre-funded accounts; smaller institutions may lack the liquidity or technology to participate","RTP only supports banks with assets over $100B","RTP is exclusively for the seven TCH owner banks"], answer:1, explanation:"RTP participation requires maintaining pre-funded liquidity accounts at TCH (funded via Fedwire). Smaller institutions may lack the technology infrastructure and/or the operational capacity to manage real-time inbound and outbound payments 24/7. FedNow was designed in part to address smaller institution participation."},

  /* ── FEDNOW (73-82) ── */
  {q:"Which organization operates the FedNow Service?", options:["The Clearing House (TCH)","Nacha","The Federal Reserve Banks","CFPB"], answer:2, explanation:"The FedNow Service is operated by the Federal Reserve Banks — the US central bank. It launched in July 2023 and provides an alternative instant payment infrastructure to TCH's RTP network."},
  {q:"In what year did FedNow officially launch?", options:["2019","2021","2023","2025"], answer:2, explanation:"FedNow launched in July 2023. After years of development, the Federal Reserve chose to build its own real-time payment infrastructure rather than rely solely on the privately-owned RTP network."},
  {q:"What is the current maximum transaction limit on the FedNow network?", options:["$500,000","$1,000,000","$5,000,000","$10,000,000"], answer:3, explanation:"The FedNow Service launched in July 2023 with an initial transaction limit of $500,000. It was raised to $1,000,000 in June 2025, and subsequently increased to $10,000,000 in November 2025 to match the RTP network limit and support high-value business payments."},
  {q:"The FedNow Liquidity Management Transfer (LMT) allows participating banks to:", options:["Overdraw their Fed reserve accounts for intraday payments","Move funds between their FedNow settlement account and their Federal Reserve master account in real time to manage liquidity","Transfer funds directly to The Clearing House pre-funded accounts","Borrow from the Fed Discount Window for RTP payments"], answer:1, explanation:"The LMT (Liquidity Management Transfer) allows FedNow participants to instantly move funds between their FedNow joint account and their Federal Reserve master account 24/7. This is critical for managing real-time liquidity when payment volumes are uneven throughout the day."},
  {q:"What was the primary policy motivation for the Federal Reserve to build FedNow rather than rely on the TCH RTP network?", options:["RTP was too slow for the Fed's needs","The Fed wanted to ensure universal access for all US financial institutions, including smaller banks and credit unions","The Fed needed a network to replace ACH","RTP was too expensive for consumers"], answer:1, explanation:"The Fed's primary motivation was universal access and public interest. RTP is owned by large banks; the Fed wanted to ensure that all ~11,000 US financial institutions (including small community banks and credit unions) could access real-time payment infrastructure — not just those that joined TCH."},
  {q:"What messaging standard does FedNow use?", options:["ISO 8583","SWIFT GPI","ISO 20022","ANSI X12 820"], answer:2, explanation:"Like RTP, FedNow uses the ISO 20022 messaging standard. This enables rich data payloads, structured remittance information, and interoperability potential with other ISO 20022-based systems globally."},
  {q:"How does FedNow's settlement model work?", options:["Pre-funded accounts at The Clearing House","Real-time debits and credits to participants' Federal Reserve master accounts","End-of-day netting via Fedwire","Bilateral correspondent accounts between banks"], answer:1, explanation:"FedNow settles by making real-time debits and credits directly to participants' Federal Reserve master (reserve) accounts. This leverages the existing Fed infrastructure and means participating banks don't need a separate pre-funded pool — any bank with a Fed master account can access FedNow liquidity."},
  {q:"Which of the following is currently a key difference between FedNow and RTP?", options:["RTP operates 24/7; FedNow only operates weekdays","FedNow is operated by the government (Fed); RTP is privately operated by bank-owned TCH","FedNow supports Request for Payment; RTP does not","RTP processes in real time; FedNow is batch-based"], answer:1, explanation:"Both systems operate 24/7. The fundamental difference is ownership and governance: FedNow is a public infrastructure operated by the Federal Reserve; RTP is privately owned by The Clearing House (a consortium of large banks). Both support ISO 20022 and real-time gross settlement."},
  {q:"Can a payment be initiated from a FedNow participant bank to an RTP participant bank if they are not on the same network?", options:["Yes — the two networks automatically interoperate","No — the two networks do not currently interoperate; both sender and receiver must be on the same network","Yes, but only for amounts under $10,000","No — FedNow can only send to other Fed member banks"], answer:1, explanation:"As of the FedNow launch, RTP and FedNow do not interoperate. Both sender's and receiver's banks must be on the same network for the payment to work. Interoperability is a major policy goal but has not yet been implemented."},
  {q:"A bank that participates in FedNow can choose to offer which of the following service tiers?", options:["Send-only, Receive-only, or both Send and Receive","Only full participation (send and receive)","Only receive until liquidity requirements are met","Pilot, Standard, and Premium tiers"], answer:0, explanation:"FedNow allows institutions to participate as Receive-only (they can receive FedNow payments but not originate them) or full Send-and-Receive participants. This lowers the bar for smaller institutions that aren't ready to manage real-time outbound payment risk."},

  /* ── WIRES (83-94) ── */
  {q:"What does RTGS stand for in the context of wire transfers?", options:["Real-Time Gross Settlement","Rapid Transaction Guaranteed Settlement","Real-Time Government Settlement","Regulated Transfer and Gross Safekeeping"], answer:0, explanation:"RTGS stands for Real-Time Gross Settlement — each wire transfer settles individually and immediately in real time, rather than being batched and netted. Fedwire is the primary US RTGS system."},
  {q:"Fedwire Funds Service is operated by:", options:["CHIPS","SWIFT","The Federal Reserve Banks","The Clearing House"], answer:2, explanation:"Fedwire Funds Service is operated by the Federal Reserve Banks. It is the primary RTGS system for large-value, time-critical US dollar transactions. All US financial institutions with Fed master accounts can access Fedwire."},
  {q:"What is CHIPS and who operates it?", options:["Clearing House Interbank Payments System, operated by The Clearing House (TCH)","Consolidated High-value Interbank Payment System, operated by the Fed","Central Hub for Institutional Payment Settlement, operated by SWIFT","Commercial High-value Immediate Payment Service, operated by Visa"], answer:0, explanation:"CHIPS (Clearing House Interbank Payments System) is operated by The Clearing House. Unlike Fedwire (RTGS), CHIPS uses multilateral netting — it accumulates transactions throughout the day and continuously nets offsetting payments, dramatically reducing the actual cash that needs to move to settle."},
  {q:"What is the primary economic advantage of CHIPS over Fedwire?", options:["CHIPS is faster","CHIPS uses multilateral netting, requiring only about 3-5% of gross transaction value to actually settle — conserving liquidity","CHIPS has lower fees","CHIPS is available 24/7 while Fedwire is not"], answer:1, explanation:"CHIPS's netting mechanism is its key advantage. Because offsetting payments between the same banks are netted against each other, the actual fund flows needed to settle are dramatically less than the gross transaction amounts. This conserves bank liquidity and is more efficient for high-volume interbank flows."},
  {q:"Which wire system handles the largest dollar volume of US domestic wire transfers daily?", options:["Fedwire","CHIPS","ACH","SWIFT"], answer:1, explanation:"CHIPS processes the largest dollar value of US domestic wire transactions — approximately $1.8 trillion daily — primarily because it handles most large-value interbank and financial market transactions. Fedwire handles more transactions by count but CHIPS leads by value."},
  {q:"What is SWIFT primarily used for?", options:["Domestic ACH payments between US banks","International financial messaging between banks and financial institutions worldwide","Real-time gross settlement of US dollar wires","Consumer payment card authorization"], answer:1, explanation:"SWIFT (Society for Worldwide Interbank Financial Telecommunication) is a secure messaging network — it does not move money itself but carries standardized financial messages (wire instructions, trade finance, securities) between over 11,000 financial institutions in 200+ countries."},
  {q:"In a correspondent banking relationship, what is a 'nostro' account?", options:["An account a bank holds at a foreign bank in the foreign bank's currency","An account a foreign bank holds at a domestic bank in domestic currency","A special settlement account at the Federal Reserve","An account used exclusively for SWIFT messages"], answer:0, explanation:"A nostro account ('our account with you') is an account that Bank A holds at Bank B, typically denominated in Bank B's local currency. For example, JPMorgan Chase's EUR account at Deutsche Bank is JPMorgan's nostro account. It holds foreign currency for facilitating cross-border payments."},
  {q:"What is a 'vostro' account?", options:["The same as a nostro account, just from the other bank's perspective","A special interbank account for SWIFT GPI payments","A Federal Reserve account used by foreign central banks","An account for trade finance letters of credit"], answer:0, explanation:"A vostro account ('your account with us') is the same bilateral account viewed from the other side. From Deutsche Bank's perspective, JPMorgan Chase's EUR account at Deutsche Bank is Deutsche Bank's vostro account. Nostro/vostro is the same account — just named differently depending on whose perspective you're using."},
  {q:"What is SWIFT GPI (Global Payments Innovation)?", options:["SWIFT's cryptocurrency payment protocol","An enhancement to SWIFT that provides end-to-end tracking, faster settlement, and fee transparency for cross-border payments","SWIFT's domestic US payment service","A SWIFT program for government-to-government transfers only"], answer:1, explanation:"SWIFT GPI is a set of enhancements to the SWIFT network that enables real-time tracking of cross-border payments (like a tracking number for wires), faster settlement (most GPI payments settle same day), and transparency of fees deducted along the correspondent chain."},
  {q:"Business Email Compromise (BEC) is most commonly used to commit which type of payments fraud?", options:["ACH debit fraud","Credit card chargebacks","Wire transfer fraud — redirecting payments to fraudulent accounts","ATM jackpotting"], answer:2, explanation:"BEC is the dominant fraud vector for wire transfers. Attackers compromise a company's email and use it to send convincing fake wire instructions (e.g., fake CFO email to accounts payable, fake vendor email changing bank account details). Wire transfers are preferred because they are fast, high-value, and difficult to reverse."},
  {q:"If a wire transfer is sent to a fraudulent account via BEC, which is true?", options:["The originating bank must reverse the wire within 24 hours","SWIFT guarantees fraud recovery for all GPI payments","There is no legal mechanism to compel the receiving bank to return funds; recovery is uncertain and depends on cooperation","The CFPB mandates full reimbursement within 10 business days"], answer:2, explanation:"Wire transfers are generally irrevocable. There is no network-mandated return process. If funds reach a fraudulent account, recovery requires law enforcement involvement (FBI, FinCEN), rapid bank-to-bank communication, and cooperation from the receiving bank — which may be in a different country. Many BEC victims never recover their funds."},
  {q:"Regulation J governs which payment systems?", options:["Consumer ACH transactions","Credit and debit card networks","Federal Reserve Banks' collection of checks and wire transfer services (Fedwire)","International SWIFT wire transfers"], answer:2, explanation:"Regulation J (12 CFR Part 210) establishes the terms and conditions under which Federal Reserve Banks collect checks and settle wire transfers over the Fedwire Funds Service. It governs the legal framework for transactions on Fed payment systems."},

  /* ── CROSS-RAIL COMPARISON (95-100) ── */
  {q:"A real estate company needs to send a $500,000 payment that must arrive and be confirmed irrevocably within 2 hours. Which rail is most appropriate?", options:["Standard ACH","Same-Day ACH","Wire (Fedwire or CHIPS)","RTP"], answer:2, explanation:"For large-value, time-critical, same-day settlement with irrevocable confirmation, wire transfer (Fedwire or CHIPS) is the traditional choice. RTP could also work if both banks are connected, but wires remain the standard for real estate closings given universal bank participation."},
  {q:"A company wants to send payroll to 10,000 employees. Which payment rail is most cost-effective and operationally appropriate?", options:["Fedwire (one wire per employee)","RTP (one RTP payment per employee)","ACH batch credit file","CHIPS"], answer:2, explanation:"ACH batch credit is the standard for payroll. A single payroll file contains all 10,000 credit entries, is submitted to the ACH operator, and distributes to each employee's RDFI. It is low cost, well-supported by all banks, and designed for exactly this use case."},
  {q:"Which payment rail is the ONLY one that currently operates as a true open-loop network available to all 10,000+ US financial institutions 24/7?", options:["RTP","FedNow","ACH","Fedwire"], answer:1, explanation:"FedNow is available to all depository institutions (banks and credit unions) that have a Fed master account — meaning virtually all ~10,000+ US financial institutions could potentially participate. RTP is also 24/7 but has more selective participation (primarily larger banks). ACH is not real-time. Fedwire is 24/7 but not for consumer-facing payments."},
  {q:"A small business wants to receive instant payments from customers through their bank's mobile app. Which rail most likely powers this experience?", options:["Standard ACH","RTP or FedNow (depending on the bank)","Fedwire","CHIPS"], answer:1, explanation:"Consumer-facing instant payment experiences (e.g., Zelle back-end for some banks, real-time business payment receipt) are powered by either RTP or FedNow — depending on which network the bank has joined. Both are 24/7 real-time credit push rails."},
  {q:"Which payment rail has NO dollar limit per transaction?", options:["RTP","FedNow","Same-Day ACH","Fedwire"], answer:3, explanation:"Fedwire Funds Service has no published transaction size limit — it can handle any dollar amount. It routinely settles multi-billion dollar transactions for financial institutions, central banks, and the US Treasury. RTP, FedNow, and Same-Day ACH all have defined per-transaction limits."},
  {q:"ACH, RTP, and FedNow are all US domestic payment rails. Which is the only one that can reach financial institutions in other countries?", options:["ACH via IAT","RTP via GPI extension","FedNow","CHIPS for domestic; SWIFT for international"], answer:0, explanation:"ACH via the IAT (International ACH Transaction) SEC code can reach foreign financial institutions, though it involves correspondent banking for the international leg. SWIFT handles the messaging for cross-border transfers. RTP and FedNow are purely domestic US networks. CHIPS is also primarily domestic with some cross-border capability."}
];
