/* ============================================================
   MODULE 7 QUESTION BANK — Innovation
   20 Questions
   ============================================================ */
window.QB_M7 = [
  {q:"What is the primary difference between a fiat-backed stablecoin and a central bank digital currency (CBDC)?", options:["Stablecoins are issued by private entities and represent a liability of the issuer; CBDCs are issued by a central bank and represent a direct liability of the sovereign monetary authority","Stablecoins are always algorithmic; CBDCs are always physical","Stablecoins can only be spent online; CBDCs can only be spent in person","There is no difference between them"], answer:0, explanation:"A fiat-backed stablecoin (like USDC or USDT) is a private liability backed by reserves held in commercial banks or Treasury bills. A CBDC is central bank money issued directly by the nation's central bank (the Fed, ECB, etc.), representing a direct claim on the central bank and carrying zero credit risk."},
  {q:"Which cross-border wholesale CBDC project involves central banks from China, Hong Kong, Thailand, and the UAE, utilizing a multi-CBDC shared platform to bypass correspondent banking?", options:["Project Nexus","Project mBridge","Project Hamilton","Project Mariana"], answer:1, explanation:"Project mBridge is a collaborative wholesale CBDC platform developed by the BIS Innovation Hub and the central banks of China, Hong Kong, Thailand, and the UAE. It allows banks to settle cross-border payments in central bank money in seconds, bypassing the traditional correspondent banking network."},
  {q:"What is the primary objective of the GENIUS Act (passed in 2025/2026) regarding stablecoins?", options:["To ban all stablecoins in the United States","To establish a formal federal regulatory framework for stablecoin issuers, requiring 1:1 liquid reserves in cash and short-term Treasuries, and bringing them under federal oversight","To mandate that stablecoins replace cash","To create a government stablecoin"], answer:1, explanation:"The GENIUS Act established a legal framework for dollar-pegged stablecoins in the US, requiring issuers to maintain 100% liquid reserves in low-risk assets (cash and short-term Treasuries) and placing them under federal supervision (such as the OCC or Fed)."},
  {q:"In the Banking-as-a-Service (BaaS) model, what is a 'Sponsor Bank'?", options:["A bank that sponsors sporting events","A bank that provides its banking charter and core payment rail integrations to fintech partners via middleware platforms","A non-bank tech company that builds customer interfaces","A venture capital firm that funds fintechs"], answer:1, explanation:"A sponsor bank is a chartered financial institution that lends its banking license and access to clearing networks (ACH, Fedwire, card networks) to non-bank fintechs or brands, allowing them to offer banking products without having to obtain a banking charter themselves."},
  {q:"What is the function of a 'BaaS Middleware Platform' (e.g. Unit, Synctera, Treasury Prime)?", options:["To manufacture physical card terminals","To act as a software layer that integrates with the sponsor bank's core banking system, exposing developer-friendly APIs and ledger management tools to the fintech app","To audit the bank's security vault","To handle direct consumer marketing"], answer:1, explanation:"BaaS middleware companies act as an API aggregator and software layer between the fintech app and the sponsor bank's legacy systems. They handle developer integration, ledger accounting, and sometimes compliance tracking."},
  {q:"What is an 'FBO' (For Benefit Of) account in a BaaS relationship?", options:["A credit line extended to the fintech founder","A pooled custodial account held at the sponsor bank that aggregates all fintech user deposits, while sub-ledgers track individual balances","A personal account for bank executives","A fund for charity donations"], answer:1, explanation:"An FBO account is a pooled account owned by the fintech (or the bank custodial agent) but held at the sponsor bank 'For the Benefit Of' the fintech's customers. The bank maintains the deposits, while the fintech's or middleware's sub-ledgers track how much money belongs to each individual user."},
  {q:"What led to the wave of regulatory consent orders against BaaS sponsor banks in 2024–2025?", options:["Banks charging too few fees","Inadequate oversight, KYC failures, and lack of direct ledger reconciliation between sponsor banks and their fintech partners' sub-ledgers","The use of mobile apps by consumers","High interest rates on savings accounts"], answer:1, explanation:"Regulators (OCC, FDIC, Fed) issued numerous consent orders because sponsor banks outsourced compliance and ledger operations to third parties without maintaining direct oversight, resulting in compliance failures (AML/KYC) and unreconciled ledger discrepancies where banks did not know whose money was in their pooled FBO accounts."},
  {q:"In 'Agentic Commerce', how are payments initiated and executed?", options:["By a human cashier at a cash register","By autonomous AI agents acting on behalf of humans, using secure APIs, virtual cards, or digital wallets to make purchases within defined parameters","By scanning a paper check via mobile app","By signing a physical document"], answer:1, explanation:"Agentic commerce involves AI agents performing transactions autonomously on behalf of users (e.g. an AI agent negotiating and purchasing API credits, booking travel, or ordering supplies) using tokenized payment systems like virtual cards or machine-to-machine wallets."},
  {q:"What is the primary technical obstacle to AI agents executing payments on traditional credit card networks?", options:["Traditional card networks require physical signatures for all transactions","AI agents cannot type card numbers","Standard card networks require manual checkout forms, multi-factor authentication (MFA) prompts (like OTP via SMS), and Captchas, which break autonomous agent flows","Card networks do not accept digital card numbers"], answer:2, explanation:"Traditional online checkouts are designed for humans — they feature Captchas, device fingerprinting, and SMS OTP/MFA challenges that autonomous scripts cannot easily bypass. Enabling agentic commerce requires specialized machine-to-machine payment rails, API keys, or tokenized virtual cards that bypass human friction."},
  {q:"What is 'Web Monetization' in the context of micropayments?", options:["Selling ads on a website","Charging a subscription fee like Netflix","An open standard that enables continuous, streaming micropayments from a user's browser wallet to a website creator in real time as the user consumes content","Selling products via e-commerce"], answer:2, explanation:"Web Monetization is a protocol that enables browsers to stream tiny fractions of a cent (micropayments) continuously to creators as a user views their web pages, providing an alternative to paywalls and intrusive advertising."},
  {q:"What is a 'wholesale' CBDC designed for?", options:["General public use for retail purchases like groceries","Interbank clearing, settlement of high-value financial market transactions, and cross-border central bank flows","P2P money transfers between family members","Small business checkouts only"], answer:1, explanation:"A wholesale CBDC is restricted to financial institutions (commercial banks, central banks). It is used to settle large-value, interbank transactions and securities markets, whereas a retail CBDC is designed for use by the general public."},
  {q:"What is a 'retail' CBDC?", options:["A CBDC used exclusively to buy goods at Walmart","A digital form of fiat currency accessible to the general public for everyday payments, serving as a digital alternative to physical cash","A stablecoin issued by a retail brand","A ledger used by suppliers to track inventories"], answer:1, explanation:"A retail CBDC is a government-issued digital currency designed to be used by consumers and businesses for everyday payments, serving as a digital counterpart to physical banknotes."},
  {q:"In stablecoin economics, what is a 'Reserve'?", options:["The minimum cash a user must have in their wallet","The pool of highly liquid assets (like cash and Treasury bills) held by the issuer to back the stablecoin, ensuring it can always be redeemed 1:1 for fiat currency","A credit line from the Fed","The stablecoin coins that have not yet been minted"], answer:1, explanation:"Reserves are the assets held by a stablecoin issuer to back the issued digital tokens. If an issuer has 1 billion USDC in circulation, they must maintain 1 billion dollars of cash and short-term Treasuries in custodial bank accounts to support 1:1 redemption."},
  {q:"What is the primary risk of an 'algorithmic' stablecoin compared to a 'fiat-backed' stablecoin?", options:["Algorithmic stablecoins are too slow","Algorithmic stablecoins rely on supply-demand incentives and uncollateralized smart contracts to maintain a peg rather than cash reserves, which can lead to a 'death spiral' panic collapse if confidence is lost","Fiat-backed stablecoins are not legal in the US","Algorithmic stablecoins are privately owned"], answer:1, explanation:"Algorithmic stablecoins (like the collapsed UST/Terra) use smart contract algorithms to balance supply and demand to maintain their peg. Lacking actual underlying hard assets (like cash reserves), they are vulnerable to panic runs where the algorithm fails to restore the peg, leading to a permanent crash."},
  {q:"In a BaaS setup, what is the role of the 'sub-ledger'?", options:["To record the bank's overhead costs","To track individual customer balances and transaction histories within a pooled custodial FBO account, keeping the database in sync with the bank's core records","To verify card security codes","To file tax returns for the bank"], answer:1, explanation:"Because the sponsor bank holds all fintech user deposits in a single pooled FBO account, the fintech/middleware sub-ledger acts as the ledger database that tracks exactly how much of that pooled balance belongs to each specific customer account."},
  {q:"What is the primary risk of BaaS middleware companies going bankrupt (as seen in the Synapse bankruptcy)?", options:["Fintech apps run out of server space","Consumers lose all their mobile devices","Frozen accounts and legal gridlock, where banks cannot verify which sub-ledger balances belong to which users because sub-ledgers were not directly reconciled on the bank's core systems","The Federal Reserve shuts down the ACH network"], answer:2, explanation:"If a middleware provider bankrupts and its databases go offline, it can cause severe freeze-outs where the sponsor banks cannot verify which part of the pooled FBO account belongs to which consumer. Lacking real-time, independent reconciliation records on the bank's core databases, customers' funds can be locked for months during legal disputes."},
  {q:"Under the GENIUS Act, which of the following is true?", options:["Stablecoins must be backed by gold","Algorithmic stablecoins are classified as commercial banks","Regulated stablecoin issuers are prohibited from engaging in fractional-reserve lending of their reserves; reserves must be 100% backed by highly liquid cash and Treasuries","Stablecoins must be issued by the Federal Reserve"], answer:2, explanation:"The GENIUS Act prohibits regulated stablecoin issuers from lending out their reserves or using fractional-reserve models. All reserves must be backed 100% by cash and Treasury bills to prevent bank runs."},
  {q:"Machine-to-Machine (M2M) payments refer to:", options:["Factory machines manufacturing physical coins","Automated transactions executed directly between hardware devices (e.g. an electric vehicle paying a charging station directly, or servers paying for bandwidth) without human intervention","Credit card swipes at gas pumps","Using an ATM to withdraw cash"], answer:1, explanation:"M2M payments are transactions executed directly between autonomous machines (IoT devices, servers, vehicles) using pre-authorized API triggers or digital wallets."},
  {q:"Which organization operates the global multi-CBDC mBridge platform?", options:["The Federal Reserve Bank of New York","The Bank for International Settlements (BIS) Innovation Hub, alongside participating central banks","Visa Inc.","The European Central Bank"], answer:1, explanation:"The BIS (Bank for International Settlements) Innovation Hub operates Project mBridge in collaboration with the central banks of Hong Kong, China, Thailand, UAE, and others."},
  {q:"What is a 'Stablecoin Settlement Corridor'?", options:["A physical hallway in a bank","A dedicated blockchain bridge or payment corridor designed to settle cross-border B2B transactions using stablecoins, bypassing correspondent banking and clearing networks","A protocol for ATM cash withdrawals","A government system to settle taxes"], answer:1, explanation:"A stablecoin settlement corridor utilizes stablecoins (like USDC) on public or private blockchains to execute cross-border commercial settlements directly, reducing transaction time from days to minutes and eliminating correspondent bank fees."}
];
