/* ============================================================
   MODULE 3 QUESTION BANK — Zelle, PayPal, Venmo
   100 Questions
   ============================================================ */
window.QB_M3 = [

  /* ── ZELLE OVERVIEW & HISTORY (1-10) ── */
  {q:"Which organization owns and operates the Zelle network?", options:["The Federal Reserve","Early Warning Services (EWS)","The Clearing House (TCH)","PayPal Holdings"], answer:1, explanation:"Zelle is owned and operated by Early Warning Services (EWS) — a fintech consortium founded and owned by seven major US banks: Bank of America, Capital One, JPMorgan Chase, PNC, Truist, U.S. Bank, and Wells Fargo."},
  {q:"In what year did Zelle officially launch to consumers?", options:["2012","2015","2017","2019"], answer:2, explanation:"Zelle launched in June 2017, replacing the fragmented clearXchange network. The rebranding and consolidation created a unified experience embedded directly in bank mobile apps."},
  {q:"Which network did Zelle replace when it launched in 2017?", options:["PayPal P2P","clearXchange","PopMoney","Dwolla"], answer:1, explanation:"Zelle replaced clearXchange — a consortium P2P network founded in 2011 by Bank of America, JPMorgan Chase, and Wells Fargo. clearXchange suffered from poor UX, slow transfers, and limited adoption before Zelle superseded it."},
  {q:"How many bank and credit union apps is Zelle embedded in (approximately, as of 2023)?", options:["500","1,000","2,200+","5,000+"], answer:2, explanation:"Zelle is embedded in more than 2,200 financial institution apps as of 2023. This massive distribution network is its key competitive advantage over standalone apps like PayPal and Venmo."},
  {q:"What was the total dollar volume of Zelle transactions in 2023?", options:["$206 billion","$406 billion","$806 billion","$1.2 trillion"], answer:2, explanation:"In 2023, Zelle processed approximately $806 billion across 2.9 billion transactions — eclipsing PayPal and Venmo combined in total dollar volume, making it the largest P2P payment network in the US."},
  {q:"Which of the following correctly describes Zelle's business model for consumers?", options:["Zelle charges 1% per transaction up to $10","Zelle is free for consumers; banks absorb costs as a retention feature","Zelle charges a $0.30 flat fee per transaction","Zelle charges merchants 2.5% while consumers pay nothing"], answer:1, explanation:"Zelle is completely free for consumers. The banks absorb the cost of offering Zelle as a competitive feature — it helps retain deposits and increases customer stickiness in their bank apps."},
  {q:"How many transactions did Zelle process in 2023?", options:["290 million","800 million","2.9 billion","5 billion"], answer:2, explanation:"In 2023, Zelle processed 2.9 billion individual transactions totaling $806 billion. The high transaction count reflects its use for everyday consumer transfers (rent, splitting bills, family transfers)."},
  {q:"Which consortium of banks OWNS Zelle's operating company (Early Warning Services)?", options:["Chase, Citi, Wells Fargo, Goldman Sachs, Morgan Stanley, BofA, U.S. Bank","Bank of America, Capital One, JPMorgan Chase, PNC, Truist, U.S. Bank, Wells Fargo","All US banks with assets over $100 billion","The Federal Reserve and FDIC jointly"], answer:1, explanation:"Early Warning Services is owned by seven banks: Bank of America, Capital One, JPMorgan Chase, PNC, Truist, U.S. Bank, and Wells Fargo. These are also the primary Zelle member banks whose customers initiated the CFPB scrutiny around fraud."},
  {q:"Before Zelle, Early Warning Services was primarily known for:", options:["Operating the RTP network","ChexSystems — the banking blacklist for account fraud","Running the CHIPS wire network","Providing FDIC insurance to small banks"], answer:1, explanation:"Before Zelle, EWS was primarily known for operating ChexSystems — a database used by banks to screen new account applicants for history of overdrafts, fraud, or account closures. EWS expanded into payments with the Zelle acquisition."},
  {q:"Zelle is primarily designed for:", options:["International money transfers","Consumer-to-consumer (P2P) and consumer-to-business payments between US bank accounts","Business-to-business (B2B) bulk payments","Replacing credit card transactions at point of sale"], answer:1, explanation:"Zelle is designed primarily for consumer P2P payments — sending money to trusted recipients like friends, family, and known businesses. It is a bank-account-to-bank-account network, not designed for e-commerce or international payments."},

  /* ── ZELLE MECHANICS & DIRECTORY (11-22) ── */
  {q:"What is the primary role of the EWS directory in the Zelle network?", options:["To store all transaction funds until settlement","To map phone numbers and email addresses to bank account routing information","To conduct fraud scoring on every Zelle transaction","To route ACH returns back to senders"], answer:1, explanation:"The EWS directory is a tokenized lookup system that maps contact tokens (phone numbers, email addresses) to bank accounts at participating financial institutions. When you send money to a phone number, EWS resolves that token to the recipient's bank and account."},
  {q:"Zelle itself moves money between banks using which underlying payment rail?", options:["Fedwire (real-time gross settlement)","RTP (Real-Time Payments)","ACH (Automated Clearing House)","CHIPS (multilateral netting)"], answer:2, explanation:"Zelle's actual money movement uses ACH — typically overnight ACH batch or Same-Day ACH. The 'instant' experience consumers feel is because banks extend intraday credit, crediting the receiver from their own books while waiting for ACH to settle in the background."},
  {q:"Why does Zelle feel 'instant' to users even though the back-end settlement is ACH?", options:["Zelle has built its own proprietary real-time payment rail","Banks extend intraday credit — they update account balances immediately on their own ledgers before ACH settles","EWS processes all transactions in under 1 second","The Fed provides same-second settlement guarantees for Zelle"], answer:1, explanation:"The instant experience is achieved through bank-level intraday credit extension. The sending bank debits the sender and credits the receiving bank's position; the receiving bank credits the receiver — all before ACH actually settles. It's a ledger trick funded by bank balance sheets."},
  {q:"In a Zelle transaction, what information does the sender share with the receiver?", options:["Full account number and routing number","Only a phone number or email address (tokenized)","Bank name and account type only","Nothing — Zelle uses facial recognition to identify the receiver"], answer:1, explanation:"One of Zelle's key privacy features is that no bank account numbers are exchanged between sender and receiver. The sender only needs the receiver's phone number or email address — the EWS directory handles the resolution to account details privately."},
  {q:"What happens when a Zelle payment is sent to someone who is NOT enrolled in Zelle?", options:["The transaction is immediately declined","The money is held in escrow by EWS for 14 days","The recipient receives an invitation to enroll; funds are pending until enrollment or expiry","The sender's bank processes it as a standard ACH push"], answer:2, explanation:"If the recipient isn't enrolled, they receive an SMS or email invitation to enroll in Zelle (via a standalone app or their bank's app). They typically have a limited window (e.g., 14 days) to enroll and claim the money. If they don't enroll, the funds revert to the sender."},
  {q:"What does 'in-network' mean in the context of a Zelle transaction?", options:["Both parties use the same bank","Both the sender's and receiver's banks participate in the Zelle network via EWS","The transaction stays within the continental US","The transaction is under Zelle's maximum limit"], answer:1, explanation:"'In-network' means both the sending and receiving banks are participants in the Zelle network (connected to EWS). In this scenario, the transfer experience is seamless and near-instant. 'Out-of-network' requires the receiver to enroll via the standalone Zelle app."},
  {q:"Who bears the intraday credit risk when Zelle credits a receiver before ACH settles?", options:["Early Warning Services (EWS)","The receiving bank","The sending bank","The Federal Reserve"], answer:1, explanation:"The receiving bank bears the intraday credit risk — it credits the receiver's account based on the instruction received, before actual ACH funds arrive. If the sending bank's ACH settlement fails (e.g., NSF), the receiving bank has already released funds and must manage the shortfall."},
  {q:"Can a consumer use a credit card to fund a Zelle payment?", options:["Yes, with a 3% surcharge","Yes, but only for amounts under $500","No — Zelle only funds from bank accounts (checking or savings)","Yes, through any Visa or Mastercard"], answer:2, explanation:"Zelle exclusively draws funds from linked bank accounts (checking or savings). Credit cards, debit cards, and digital wallets cannot be used to fund Zelle payments. This bank-only funding model is integral to Zelle's architecture."},
  {q:"What is the typical daily Zelle transaction limit for a consumer using Chase?", options:["$500","$1,000","$2,500","$10,000"], answer:2, explanation:"Chase's Zelle daily limit for most consumer accounts is $2,500. Limits vary significantly by bank — from $500/day for the standalone Zelle app to $3,500/day at some major banks. Limits are set by the sending bank, not by EWS."},
  {q:"Which of the following is Zelle LEAST suited for?", options:["Splitting a restaurant bill with friends","Paying a trusted landlord rent","Purchasing goods from a stranger on Facebook Marketplace","Sending money to a family member"], answer:2, explanation:"Zelle has no buyer protection — once sent to an enrolled receiver, funds cannot be recovered. Purchasing from strangers (marketplace transactions) is extremely high-risk. If the item never arrives, Zelle has no mechanism to recover funds. PayPal G&S or credit card is far more appropriate."},
  {q:"Zelle Pay with Zelle (ZPwZ) refers to:", options:["The Zelle app available for standalone download","In-store QR code payments at select merchants using Zelle","Zelle's B2B payment service for businesses","Zelle's international transfer feature"], answer:1, explanation:"ZPwZ (Pay with Zelle) is a merchant-facing feature in pilot that allows consumers to scan a QR code at a merchant's point of sale and pay directly from their bank account via Zelle. It's in early-stage deployment as of 2025."},
  {q:"Zelle transactions, once sent to an enrolled receiver, are best described as:", options:["Fully reversible within 24 hours","Reversible only for amounts over $1,000","Irrevocable — there is no network mechanism to pull funds back","Reversible if both banks agree within 5 business days"], answer:2, explanation:"Once a Zelle payment posts to an enrolled receiver's account, it cannot be reversed through Zelle or the banking system. This is by design (bank-to-bank credit with no escrow), but it is the primary consumer risk factor — particularly in scam scenarios."},

  /* ── ZELLE FRAUD & REG E (23-34) ── */
  {q:"The Electronic Fund Transfer Act (EFTA) / Regulation E covers which category of Zelle transactions?", options:["All Zelle transactions, authorized or not","Only transactions over $500","Only unauthorized transactions (e.g., account takeover) — NOT authorized transactions where the consumer was scammed","All consumer Zelle debits, but not credits"], answer:2, explanation:"Reg E protects consumers only for UNAUTHORIZED electronic fund transfers — where someone else initiated the transaction without the consumer's knowledge (e.g., account takeover fraud). If the consumer themselves sent the payment (even if scammed), that is an 'authorized' transaction and Reg E does not mandate reimbursement."},
  {q:"What is a 'bank impersonation scam' in the context of Zelle fraud?", options:["A hacker who physically impersonates a bank teller","A fraudster who calls posing as the victim's bank fraud department and convinces them to send Zelle payments to 'protect' their account","A scheme where fake banks recruit new customers","A fraudster who creates fake bank websites to steal login credentials"], answer:1, explanation:"In the most common Zelle scam, a fraudster calls or texts posing as the victim's bank fraud team, claims suspicious activity on the account, and convinces the victim to send Zelle payments to a 'safe account' to 'protect' their funds. The consumer initiates the payment — making it legally 'authorized' under Reg E."},
  {q:"In 2023, large Zelle-owning banks agreed to voluntarily reimburse consumers for which specific fraud type?", options:["All Zelle scams, regardless of type","Romance scams only","Marketplace scams only","Bank impersonation scams (fraudsters posing as the consumer's own bank)"], answer:3, explanation:"Under Congressional and CFPB pressure, the major Zelle owner banks agreed in 2023 to voluntarily reimburse certain consumers who were victimized by bank impersonation scams. This was a partial concession — it left out romance scams, marketplace fraud, and other authorized-but-fraudulent payment types."},
  {q:"In December 2024, the CFPB took which action regarding Zelle and its owner banks?", options:["Approved Zelle's business model as consumer-safe","Filed a lawsuit against EWS and the seven Zelle owner banks over inadequate fraud protections","Ordered Zelle to cap all transactions at $500","Mandated Zelle to reimburse all fraud victims retroactively"], answer:1, explanation:"In December 2024, the CFPB filed suit against Early Warning Services and the seven Zelle owner banks, alleging they knowingly launched and promoted Zelle despite awareness of widespread fraud and failed to implement adequate consumer protections."},
  {q:"Under Regulation E, what is the maximum consumer liability for an UNAUTHORIZED Zelle transaction if reported within 2 business days?", options:["$0","$50","$500","Unlimited"], answer:1, explanation:"If an unauthorized electronic fund transfer is reported within 2 business days of the consumer learning of the loss, the consumer's maximum liability under Reg E is $50. This applies to true unauthorized transactions (account takeover) — not to authorized but fraudulent payments."},
  {q:"What is the key distinction between 'unauthorized' and 'authorized-but-fraudulent' in the context of Zelle?", options:["Dollar amount — under $1,000 is authorized, over $1,000 is unauthorized","Who initiated the transaction — unauthorized means the fraudster controlled the account; authorized means the consumer themselves sent the money (even if deceived)","Timing — same-day transactions are unauthorized","The bank determines which category applies based on IP address verification"], answer:1, explanation:"The Reg E distinction is binary: Did the consumer themselves initiate the transaction? If yes — even if they were deceived by a scammer — it is 'authorized.' Only transactions where someone else gained control of the account and sent money without the consumer's knowledge are 'unauthorized' and covered by Reg E."},
  {q:"Which Zelle fraud type is a 'romance scam'?", options:["Unauthorized — attacker hacked the account","Authorized-but-fraudulent — consumer knowingly sent money to a scammer they believed was a romantic partner","A technical glitch where payments are duplicated","A corporate fraud type covered by commercial banking agreements"], answer:1, explanation:"Romance scams are authorized-but-fraudulent payments. The consumer willingly sends money to a person they've developed an online relationship with — but that person is a fraudster who fabricated the relationship to extract money. The consumer authorized every payment, leaving them unprotected under Reg E."},
  {q:"What should a Zelle fraud victim do immediately upon discovering they sent money to a scammer?", options:["Contact Zelle's website chat for an immediate reversal","Contact their bank immediately, file a police report, and report to the FTC at ReportFraud.ftc.gov","Wait 30 days to see if the money returns automatically","File a chargeback with Visa or Mastercard"], answer:1, explanation:"Immediate bank contact is critical — though recovery is unlikely once funds are in an enrolled receiver's account, the bank may be able to flag the account. A police report is required for most fraud reimbursement requests. FTC reporting creates a record used in regulatory enforcement. Zelle has no reversal mechanism."},
  {q:"Which of the following IS covered by Reg E for Zelle users?", options:["Sending money to a fake landlord for an apartment deposit","Being tricked by a fake IRS agent to pay 'back taxes' via Zelle","A hacker gaining access to your mobile banking app and sending Zelle payments to themselves","A marketplace purchase that never arrived"], answer:2, explanation:"Account takeover — where a hacker gains access to your account and initiates Zelle payments without your knowledge — is a TRUE unauthorized transaction covered by Reg E. In this case, the bank must investigate and reimburse eligible losses per Reg E timelines."},
  {q:"What is the typical deadline for an RDFI to return a Zelle-related unauthorized ACH transaction?", options:["2 business days","10 business days","60 calendar days","180 calendar days"], answer:2, explanation:"For consumer ACH unauthorized return claims (which underpin some Zelle fraud claims when ACH is the settlement rail), the RDFI has up to 60 calendar days from the settlement date to return the entry using return codes like R10 or R07."},
  {q:"EWS (Early Warning Services) was also known for which service before Zelle?", options:["SWIFT messaging","ChexSystems (banking risk database)","The Nacha ACH Operator","Visa Direct"], answer:1, explanation:"Before Zelle, EWS was best known for operating ChexSystems — a consumer reporting agency that banks use to screen checking account applicants for prior account misuse, NSFs, or fraud. This background in bank risk data is why the seven major banks trusted EWS to build Zelle."},
  {q:"A consumer's Zelle account limit is $500/day. They try to send $600 in one transaction. What happens?", options:["Zelle charges a fee and processes the $600","The transaction is declined by the sending bank","Zelle splits the transaction into two separate $300 payments","EWS automatically increases the limit for this transaction"], answer:1, explanation:"The sending bank's Zelle limits are hard limits — the transaction would be declined. The sender would need to split into multiple transactions on different days, contact their bank to request a limit increase, or use a different payment method for larger amounts."},

  /* ── PAYPAL OVERVIEW & HISTORY (35-42) ── */
  {q:"PayPal was founded in which year and by whom?", options:["1995 by Jeff Bezos and Elon Musk","1998 by Max Levchin, Peter Thiel, and Luke Nosek (later merging with Elon Musk's X.com)","2000 by Elon Musk and Confinity","2002 following eBay's acquisition"], answer:1, explanation:"PayPal was founded in 1998 by Max Levchin, Peter Thiel, and Luke Nosek as Confinity. In 2000, Confinity merged with Elon Musk's X.com to form the combined PayPal. IPO'd in 2002 and immediately acquired by eBay for $1.5B."},
  {q:"What is PayPal's regulatory classification in the United States?", options:["Federally chartered bank","Licensed money transmitter in all 50 states, registered as an MSB with FinCEN","A payment card network like Visa","An FDIC-insured depository institution"], answer:1, explanation:"PayPal is a licensed money transmitter — it holds money transmitter licenses in all 50 US states and DC (each obtained separately from state banking regulators) and is registered as a Money Services Business (MSB) with FinCEN. It is NOT a bank."},
  {q:"When did PayPal spin off from eBay as an independent public company?", options:["2002","2009","2015","2020"], answer:2, explanation:"PayPal was spun off from eBay in July 2015 as an independent, publicly traded company. This followed years of activist investor pressure arguing that PayPal's growth was being constrained by its eBay relationship."},
  {q:"How many active accounts did PayPal have globally as of 2023?", options:["126 million","226 million","426 million","826 million"], answer:2, explanation:"PayPal had approximately 426 million active accounts globally in 2023, operating in 200+ markets and supporting 25 currencies. 'Active' is defined as accounts that made at least one transaction in the prior 12 months."},
  {q:"PayPal acquired Braintree in 2013 for $800 million. What key asset came with that acquisition?", options:["Venmo","Square's point-of-sale technology","Stripe's developer API","iZettle's mobile card reader"], answer:0, explanation:"When PayPal acquired Braintree for $800 million in 2013, Venmo (which Braintree had acquired from its founders for $26.2 million in 2012) came along with the deal. It became one of PayPal's most strategically valuable consumer-facing assets."},
  {q:"What was PayPal's total revenue in 2023?", options:["$9.8 billion","$18.3 billion","$29.8 billion","$41.2 billion"], answer:2, explanation:"PayPal's 2023 revenue was approximately $29.8 billion, generated from transaction fees (merchant MDR), interest income on balances held, value-added services, and subscriptions. 2023 also marked a strategic shift toward profitability over user growth."},
  {q:"Which of the following best distinguishes PayPal from Zelle architecturally?", options:["PayPal uses Fedwire; Zelle uses ACH","PayPal operates a digital wallet (stored-value account); Zelle has no wallet and sends directly bank-to-bank","PayPal is US-only; Zelle operates in 50 countries","PayPal requires a credit card; Zelle requires a bank account"], answer:1, explanation:"The fundamental architectural distinction: PayPal is a digital wallet — it holds monetary value on its own ledger. Zelle has NO wallet — payments go directly from one bank account to another with EWS serving only as a directory and messaging layer."},
  {q:"Is PayPal bound by Regulation E in the same way as a bank?", options:["Yes — PayPal is fully subject to Reg E as a large MSB","No — as a money transmitter, PayPal has its own dispute resolution process, though the CFPB has supervisory authority over large nonbank payment providers","No — PayPal is completely exempt from consumer protection regulation","Yes — PayPal must have FDIC insurance and follow all bank regulations"], answer:1, explanation:"PayPal isn't subject to Reg E in the same way banks are. It has its own Buyer/Seller Protection policies. However, the CFPB has supervisory authority over large nonbank payment companies, meaning PayPal faces regulatory scrutiny similar (though not identical) to what banks experience under Reg E."},

  /* ── PAYPAL ARCHITECTURE & FEES (43-54) ── */
  {q:"When both the buyer and seller have PayPal balances and conduct a PayPal transaction, what actually happens to the money?", options:["It moves via ACH between their linked bank accounts","It is a purely internal ledger entry — no external network is involved","It routes through Visa/Mastercard","It is held by PayPal for 24 hours before posting"], answer:1, explanation:"When both parties have PayPal balances, the transaction is entirely internal — PayPal debits one ledger entry and credits another. No ACH, no card network, no external settlement. This is extremely efficient and nearly costless for PayPal to process."},
  {q:"What does PayPal's 'Instant Transfer' feature use to push funds to a seller's bank account in minutes?", options:["ACH Same-Day","Fedwire","Visa Direct or Mastercard Send (push-to-debit-card)","SWIFT GPI"], answer:2, explanation:"PayPal's Instant Transfer uses push-to-debit-card rails (Visa Direct or Mastercard Send) to deliver funds to the seller's linked debit card within 30 minutes. This is why a debit card must be linked — the card number, not a routing/account number, receives the push payment."},
  {q:"What is the fee for PayPal's Instant Transfer of balance to a linked debit card?", options:["Free","$0.99 flat","1.75% (min $0.25, max $25)","3% like credit card transactions"], answer:2, explanation:"PayPal charges 1.75% of the transfer amount for Instant Transfer, with a minimum of $0.25 and maximum of $25. This fee covers PayPal's cost of using the push-to-debit card rails (Visa Direct/Mastercard Send) plus PayPal's revenue margin."},
  {q:"What is PayPal's standard fee for a merchant receiving a payment through PayPal Checkout?", options:["1.49% + $0.10","2.99% + $0.49","3.49% + $0.49","5% for all transactions"], answer:1, explanation:"PayPal's standard online checkout rate is 2.99% + $0.49 per transaction (for most consumer card or PayPal balance payments). The higher 3.49% + $0.49 rate applies to invoices, Venmo transactions, and certain card types. In-store QR code transactions have a lower rate (2.29% + $0.09) due to lower fraud risk."},
  {q:"PayPal's 'Friends and Family' (F&F) payment option is free, but what major risk does it carry?", options:["No risk — F&F is fully protected by PayPal Purchase Protection","F&F payments have a $200 limit","F&F payments carry NO buyer protection — if goods never arrive, PayPal cannot help","F&F payments are taxable under IRS rules regardless of amount"], answer:2, explanation:"Friends & Family (F&F) transactions explicitly exclude PayPal Purchase Protection. F&F is designed for personal payments to known contacts, not commerce. Scammers exploit this by convincing buyers to pay via F&F to avoid leaving a purchase record — with no recourse if goods never arrive."},
  {q:"PayPal's Purchase Protection covers buyers in which scenarios?", options:["Only unauthorized transactions","Item not received (INR) and Item Significantly Not as Described (SNAD), on Goods & Services transactions","All PayPal transactions including F&F","Only transactions above $100"], answer:1, explanation:"PayPal Purchase Protection applies to Goods & Services transactions (not F&F) and covers: (1) Item Not Received — buyer paid but item never arrived; (2) Item Significantly Not as Described — item arrived but materially differs from the listing. Buyer has up to 180 days to file a dispute."},
  {q:"PayPal Seller Protection shields sellers against which types of claims?", options:["All chargebacks, regardless of reason","Unauthorized payment claims and Item Not Received claims, when seller ships to confirmed address with tracking","Friendly fraud and Item Not as Described chargebacks","All claims from buyers who paid with credit cards"], answer:1, explanation:"Seller Protection applies when: the payment is for a tangible item, the seller ships to the PayPal-confirmed address, tracking shows delivery, and the order is marked shipped in PayPal. It covers unauthorized payment claims and Item Not Received claims — but NOT SNAD (item not as described) or intangible goods."},
  {q:"PayPal Credit is a revolving credit product. Who is the actual lender/issuer of PayPal Credit?", options:["PayPal Bank NA","Synchrony Bank","JPMorgan Chase","Goldman Sachs (Marcus)"], answer:1, explanation:"PayPal Credit is issued by Synchrony Bank (not PayPal itself — remember, PayPal is not a bank). Synchrony Bank holds the credit risk and issues the credit line embedded in PayPal's checkout flow. PayPal earns revenue through a marketing/partnership arrangement with Synchrony."},
  {q:"PayPal's chargeback fee is:", options:["$10 per dispute","$20 per dispute, refunded if the merchant wins","$45 per dispute","5% of the disputed amount"], answer:1, explanation:"PayPal charges $20 per chargeback opened by a buyer. If the merchant successfully disputes the chargeback and wins, the $20 fee is refunded. This structure is designed to cover PayPal's dispute resolution costs while incentivizing merchants to maintain good practices."},
  {q:"Are PayPal account balances FDIC insured?", options:["Yes — up to $250,000, same as a bank","No — PayPal is not a bank; balances are held in pooled accounts at partner banks but are not directly FDIC insured","Yes — PayPal holds a special FDIC insurance policy","No — PayPal balances have no protection whatsoever"], answer:1, explanation:"PayPal balances are NOT directly FDIC insured. PayPal holds customer funds in pooled accounts at FDIC-insured partner banks, but pass-through insurance requires specific conditions (proper titling, record-keeping). PayPal Savings (via Synchrony Bank) IS separately FDIC insured as a bank product."},
  {q:"PayPal operates in how many countries/markets globally?", options:["50","100","200+","Globally unlimited"], answer:2, explanation:"PayPal operates in 200+ markets globally, supporting 25 currencies. This international reach is one of PayPal's key advantages over Zelle (US-only) and Venmo (US-only). International P2P transfers and cross-border merchant payments are core PayPal use cases."},
  {q:"What does '3D Secure (3DS)' do in the context of PayPal card-funded transactions?", options:["It adds three layers of encryption to the payment data","It authenticates the cardholder during checkout, shifting fraud liability from merchant to the card issuer","It splits the transaction across three payment methods","It is a three-day hold on PayPal transactions for fraud review"], answer:1, explanation:"3D Secure is an issuer authentication protocol. When triggered during a PayPal card-funded purchase, the card issuer authenticates the consumer (via OTP, biometric, or risk-based assessment). If authenticated, fraud liability shifts from PayPal/merchant to the card issuer — protecting PayPal from unauthorized transaction chargebacks."},

  /* ── PAYPAL REGULATORY & COMPLIANCE (55-64) ── */
  {q:"At what threshold does PayPal issue a 1099-K to sellers?", options:["$5,000 per year","$2,500 per year","$600 per year in goods and services payments","$20,000 per year"], answer:2, explanation:"PayPal reports Goods & Services payments to the IRS via Form 1099-K for sellers receiving $600 or more annually. This threshold (reduced from $20,000 under ARPA legislation) caused significant controversy about casual-seller taxation and was subject to IRS implementation delays."},
  {q:"What does it mean that PayPal is registered as a 'Money Services Business (MSB)' with FinCEN?", options:["PayPal is chartered as a federal bank","PayPal must comply with Bank Secrecy Act requirements: AML programs, SAR filing, CTR filing, and KYC","PayPal is regulated like a credit union","MSB status exempts PayPal from all state regulation"], answer:1, explanation:"As an MSB registered with FinCEN, PayPal must maintain a comprehensive Anti-Money Laundering (AML) program, file Suspicious Activity Reports (SARs), file Currency Transaction Reports (CTRs) for $10,000+ cash equivalents, and conduct Know Your Customer (KYC) verification on account holders."},
  {q:"How many state money transmitter licenses does PayPal hold in the US?", options:["10 (one per Fed district)","25 (all states where it operates)","51 (all 50 states plus DC, each separately)","Just one federal MSB registration covers all states"], answer:2, explanation:"PayPal holds separate money transmitter licenses in all 50 states plus the District of Columbia — 51 licenses in total, each obtained through individual state banking regulators. This is a massive regulatory burden and a significant barrier to entry for competitors."},
  {q:"Can PayPal freeze or hold a seller's funds? Under what circumstances?", options:["No — once a transaction posts, PayPal cannot touch the funds","Yes — PayPal can hold funds for up to 21 days for new or high-risk sellers, or freeze accounts suspected of policy violations","Only the seller's bank can freeze PayPal-held funds","Yes, but only for amounts over $10,000"], answer:1, explanation:"PayPal can and does place holds on seller funds — typically 21-day holds for new sellers or those with elevated risk (high dispute rates, unusual transaction patterns, suspicious activity). PayPal can also permanently freeze accounts for Terms of Service violations pending investigation."},
  {q:"Which regulatory body has supervisory authority over PayPal's consumer protection practices?", options:["OCC (Office of the Comptroller of the Currency)","FDIC","CFPB (Consumer Financial Protection Bureau)","SEC (Securities and Exchange Commission)"], answer:2, explanation:"The CFPB has supervisory and examination authority over large nonbank payment providers, including PayPal. The CFPB's nonbank supervision rule (2023) specifically targets companies with over 5 million annual consumer payment transactions."},
  {q:"PayPal's OFAC screening requirement means:", options:["PayPal must verify all users are US citizens","PayPal must screen transactions and users against OFAC's Specially Designated Nationals (SDN) list to prevent dealings with sanctioned countries/individuals","PayPal must file a report with OFAC for every international transaction","OFAC must approve PayPal's business license annually"], answer:1, explanation:"OFAC (Office of Foreign Assets Control) screening is a mandatory BSA/AML compliance requirement. PayPal must screen all users and transactions against the SDN list and other sanctions lists — blocking or rejecting transactions involving sanctioned countries, entities, or individuals."},
  {q:"What is 'account takeover (ATO)' fraud in the context of PayPal?", options:["A fraudster physically takes over a PayPal retail location","An attacker gains unauthorized access to a user's PayPal account (via credential stuffing, phishing, or SIM swap) and drains balances or initiates unauthorized transactions","A legitimate corporate acquisition of PayPal by another fintech","A user intentionally closes their PayPal account and opens a new one"], answer:1, explanation:"ATO is the most common PayPal fraud type. Attackers obtain login credentials through data breaches, phishing emails, or SIM-swap attacks to hijack the victim's phone number and bypass 2FA. Once in, they transfer balances out, add new bank accounts, or make fraudulent purchases."},
  {q:"PayPal's $600 1099-K threshold applies to which payment type?", options:["All PayPal transactions, including F&F","Only Friends & Family payments","Only Goods & Services payments (commercial transactions)","Any single transaction over $600"], answer:2, explanation:"The 1099-K applies only to Goods & Services transactions — commercial payments from buyers to sellers. Personal F&F payments are not reported (they're not income). The threshold confusion caused widespread concern among casual sellers and gig workers."},
  {q:"Can a PayPal account be used for cryptocurrency transactions?", options:["No — PayPal is strictly fiat currency only","Yes — PayPal allows buying, selling, and holding select cryptocurrencies, automatically converting to USD for purchases","Yes — PayPal sends BTC directly on the Bitcoin blockchain","Only PayPal business accounts can use crypto"], answer:1, explanation:"PayPal allows users to buy, sell, and hold select cryptocurrencies (Bitcoin, Ethereum, Litecoin, Bitcoin Cash) within the PayPal app. When a consumer pays with crypto at checkout, PayPal automatically converts it to USD at the time of the transaction. PayPal earns a spread on crypto trades."},
  {q:"What is the key risk when a seller receives a PayPal payment funded by the buyer's credit card?", options:["The transaction takes 7 days to settle","The buyer can dispute the charge with their credit card issuer (chargeback), and PayPal may hold the seller liable","The seller pays double fees","Credit-card-funded PayPal payments don't receive Purchase Protection"], answer:1, explanation:"When a buyer's PayPal payment is funded by their credit card, the buyer has two dispute avenues: PayPal's own dispute process AND a chargeback through their card issuer. Sellers can face a card-level chargeback even if they won a PayPal dispute — a significant risk for merchants with high credit-card-funded sales."},

  /* ── VENMO OVERVIEW & MECHANICS (65-74) ── */
  {q:"Venmo was founded in what year and by whom?", options:["2007 by Peter Thiel","2009 by Andrew Kortina and Iqram Magdon-Ismail","2011 by PayPal internally","2013 when PayPal acquired Braintree"], answer:1, explanation:"Venmo was founded in 2009 by Andrew Kortina and Iqram Magdon-Ismail, who met as University of Pennsylvania roommates. The original concept was SMS-based payments. The social feed came later and became the product's defining feature."},
  {q:"How did PayPal come to own Venmo?", options:["PayPal built Venmo internally in 2010","PayPal acquired Venmo directly from its founders in 2012 for $26 million","PayPal acquired Braintree for $800 million in 2013; Venmo came with Braintree","The Federal Reserve assigned Venmo to PayPal as part of a regulatory settlement"], answer:2, explanation:"The ownership chain: Braintree acquired Venmo from its founders for $26.2 million in 2012. PayPal then acquired Braintree for $800 million in 2013. Venmo came along as part of the Braintree acquisition — a remarkable return on investment."},
  {q:"What is Venmo's defining social feature that distinguishes it from other P2P apps?", options:["Venmo uses facial recognition to verify recipients","A social feed where transaction descriptions (not amounts) are visible to friends by default","Venmo sends physical gift cards to recipients","Venmo broadcasts payment confirmations via SMS to both parties"], answer:1, explanation:"Venmo's social feed — where payment emojis and descriptions appear on a timeline visible to friends — is its core differentiator. It drove viral adoption among college students and millennials by making payments a social activity. Transaction amounts are hidden; descriptions are public to friends by default."},
  {q:"Approximately how many active users does Venmo have?", options:["15 million","38 million","78 million","150 million"], answer:2, explanation:"Venmo has approximately 78 million active accounts as of 2023 — making it the dominant US consumer P2P app by user count. However, Zelle surpassed Venmo in total dollar volume."},
  {q:"What is the fee for sending money via Venmo using a credit card?", options:["Free","1%","3%","5%"], answer:2, explanation:"Venmo charges a 3% fee when a P2P payment is funded by a credit card. Bank account, debit card, and Venmo balance funding are free for P2P. The 3% fee is Venmo's way of recouping the credit card interchange it must pay to the card network and issuer."},
  {q:"The Venmo Debit Card is issued on which card network?", options:["Visa","Mastercard","American Express","Discover"], answer:1, explanation:"The Venmo Debit Card is issued on the Mastercard network. It is funded by the user's Venmo balance and can be used anywhere Mastercard is accepted, enabling users to spend their Venmo balance in the physical world."},
  {q:"The Venmo Credit Card is issued by which bank?", options:["PayPal Bank NA","Synchrony Bank (on the Visa network)","Chase (on the Mastercard network)","Capital One (on the Visa network)"], answer:1, explanation:"The Venmo Credit Card is a Visa credit card issued by Synchrony Bank. It offers 3% cash back on the top spend category, 2% on the second category, and 1% elsewhere. Cash back is deposited directly to the user's Venmo balance."},
  {q:"What rewards does the Venmo Credit Card offer?", options:["1.5% flat cash back on all purchases","2 points per dollar on all purchases redeemable for travel","3% on top spend category / 2% on second category / 1% elsewhere","5% on groceries and 2% on everything else"], answer:2, explanation:"The Venmo Credit Card automatically detects the user's top spend category each month and awards 3% cash back on it, 2% on the second-highest category, and 1% everywhere else. Cash back posts to the Venmo balance."},
  {q:"Internal Venmo-to-Venmo transfers settle in what timeframe?", options:["Next business day via ACH","Same day via Fedwire","Instantly — they are internal ledger entries on PayPal's servers","Within 30 minutes via push-to-debit"], answer:2, explanation:"Venmo-to-Venmo transfers are purely internal ledger movements on PayPal's servers. No external network is involved. The sender's Venmo balance is debited and the receiver's balance is credited instantly — it's the same as moving money between two columns in a spreadsheet."},
  {q:"Venmo is available for use in which geographic markets?", options:["US and Canada","US and Mexico","US and European Union","United States only"], answer:3, explanation:"Venmo is a US-only product. You can only send and receive Venmo payments between US-based users with US bank accounts. This is in contrast to PayPal, which operates in 200+ markets globally. Venmo cannot be used for international transfers."},

  /* ── VENMO SETTLEMENT & PRIVACY (75-84) ── */
  {q:"How long does a standard (free) Venmo bank transfer take?", options:["Immediate","Same business day","1-3 business days","5-7 business days"], answer:2, explanation:"Standard transfers from Venmo balance to a linked bank account via ACH take 1-3 business days and are free. Instant Transfer (1.75% fee, min $0.25, max $25) delivers funds within 30 minutes via push-to-debit-card."},
  {q:"Venmo Instant Transfer uses which infrastructure to deliver funds rapidly?", options:["FedNow","ACH Same-Day","Visa Direct or Mastercard Send (push-to-debit)","RTP (The Clearing House)"], answer:2, explanation:"Venmo's Instant Transfer uses push-to-debit-card rails — Visa Direct or Mastercard Send — to credit the user's linked debit card within 30 minutes. The debit card's network, not ACH, carries the instant credit."},
  {q:"What is the fee for Venmo's Instant Transfer?", options:["Free","$0.25 flat","1.75% (min $0.25, max $25)","3% same as credit card"], answer:2, explanation:"Instant Transfer costs 1.75% of the transfer amount with a minimum of $0.25 and maximum of $25. For a $100 transfer, the fee is $1.75; for $1,500, it's $25 (the cap). This is identical to PayPal's Instant Transfer fee."},
  {q:"Venmo's default privacy setting for new transactions is:", options:["Private — only sender and receiver see it","Public — anyone on Venmo can see it","Friends — visible to both parties' Venmo friend lists","Business — visible to the business profile only"], answer:2, explanation:"Venmo's default privacy setting is 'Friends' — transaction descriptions (not amounts) are visible to both parties' Venmo friend lists. Users can change each transaction to 'Private' or keep the default. Many users don't realize their transactions are visible to all mutual Venmo connections."},
  {q:"In 2019, a researcher caused controversy by revealing which Venmo privacy issue?", options:["Venmo was storing users' actual bank credentials","The researcher found President Trump's public Venmo social graph by exploiting Venmo's public API","Venmo was sharing transaction data with Facebook","Venmo's fraud detection algorithm was racially biased"], answer:1, explanation:"Researcher Hang Do Thi Duc used Venmo's public API to scrape and analyze public transaction data, ultimately finding and publishing Donald Trump's Venmo social network (connections and interactions). This highlighted the serious privacy risks of Venmo's public-by-default social feed."},
  {q:"Venmo balances are FDIC insured up to $250,000. True or false?", options:["True — Venmo holds funds at FDIC-insured banks, providing full pass-through coverage","False — Venmo balances are held in pooled accounts at partner banks but are not directly FDIC insured","True — Venmo has its own FDIC insurance policy","False — Venmo balances have zero regulatory protection"], answer:1, explanation:"False. Venmo balances are NOT directly FDIC insured. PayPal holds customer funds in pooled accounts at FDIC-insured banks, but pass-through insurance is not automatic — it requires proper titling and record-keeping that may not apply to all Venmo balance holders. Venmo Savings (via Synchrony Bank) IS separately FDIC insured."},
  {q:"Using Venmo for business transactions on a personal account is:", options:["Allowed and encouraged","Prohibited by Venmo's Terms of Service; can result in account freeze or termination","Allowed for amounts under $1,000 per month","Required to be disclosed to the IRS but otherwise permitted"], answer:1, explanation:"Venmo's Terms of Service explicitly prohibit using personal accounts for commercial business transactions. Venmo has frozen and terminated accounts found to be conducting business volume under personal profiles. Businesses must use Venmo Business Profiles, which charge 1.9% + $0.10 per transaction."},
  {q:"The IRS Form 1099-K reporting threshold of $600 applies to Venmo in which context?", options:["All Venmo transactions between any two users","Only Venmo business profile transactions where goods or services are paid","Any Venmo transaction over $600 per year including F&F","All Venmo transactions from users who identify themselves as businesses"], answer:1, explanation:"Venmo (via PayPal) reports Goods & Services payments to the IRS via 1099-K when a seller receives $600+ annually. Personal F&F payments are excluded. Business profile transactions are included. The line can blur — hence the importance of using G&S for any commercial transaction."},
  {q:"What BSA/AML framework governs Venmo?", options:["Venmo has its own separate AML program independent of PayPal","Venmo is covered under PayPal's FinCEN MSB registration and AML program as a subsidiary","Venmo is regulated by each state's banking regulator independently","As a social app, Venmo is exempt from BSA requirements"], answer:1, explanation:"Venmo is a wholly-owned PayPal subsidiary and is covered under PayPal's FinCEN MSB registration and enterprise-wide AML program. Venmo transactions are subject to the same KYC, SAR filing, OFAC screening, and transaction monitoring requirements as all PayPal transactions."},
  {q:"A user tries to use Venmo to send money to a friend in the United Kingdom. What happens?", options:["Venmo processes it for a 3% international transfer fee","Venmo converts the currency at the market rate","The transaction is declined — Venmo is US-only","Venmo routes it through PayPal's international network automatically"], answer:2, explanation:"Venmo cannot send money internationally. It is strictly US-to-US bank account transfers only. The transaction would be declined or the option wouldn't appear. For international transfers, the user would need to use PayPal (which supports 200+ markets) or a dedicated international transfer service."},

  /* ── CROSS-PLATFORM COMPARISON (85-100) ── */
  {q:"Which of the three platforms (Zelle, PayPal, Venmo) operates internationally?", options:["Zelle","PayPal","Venmo","All three"], answer:1, explanation:"Only PayPal operates internationally — in 200+ markets supporting 25 currencies. Zelle is US-only bank-to-bank. Venmo is US-only consumer wallet. International reach is one of PayPal's core strategic advantages."},
  {q:"Which platform offers NO buyer protection for any transaction type?", options:["PayPal F&F","Venmo F&F","Zelle (all transactions)","Venmo G&S"], answer:2, explanation:"Zelle offers zero buyer protection for any transaction. All Zelle transactions — regardless of purpose — have no protection mechanism. PayPal and Venmo at least offer protection on Goods & Services transactions. This makes Zelle inappropriate for purchases from unknown parties."},
  {q:"Which of the following is TRUE about PayPal balances vs. Zelle?", options:["Both are FDIC insured","Zelle bank accounts are FDIC insured; PayPal balances are not directly insured","PayPal balances are FDIC insured; Zelle transactions are not","Neither is FDIC insured"], answer:1, explanation:"Because Zelle sends money directly between bank accounts, the funds remain in FDIC-insured bank accounts. PayPal balances are stored in PayPal's own ledger (not in the user's bank account) and are NOT directly FDIC insured."},
  {q:"For a marketplace sale between strangers (e.g., used furniture on Facebook Marketplace), which is the safest payment method?", options:["Zelle","Venmo Friends & Family","PayPal Goods & Services","Cash App"], answer:2, explanation:"PayPal Goods & Services is the safest option for marketplace transactions with strangers — it provides Purchase Protection (buyer refund if item not received or SNAD) and Seller Protection (coverage against unauthorized transaction chargebacks). Zelle and Venmo F&F offer no protection at all."},
  {q:"All three platforms (Zelle, PayPal, Venmo) are subject to IRS 1099-K reporting. True or false?", options:["True — all three report to the IRS","False — only PayPal reports; Zelle and Venmo do not","Partially true — PayPal and Venmo report; Zelle payments are reported by the underlying banks","False — none of them are required to file 1099-Ks"], answer:2, explanation:"PayPal and Venmo (as the same entity) report G&S payments via 1099-K. Zelle itself does not report to the IRS — but the underlying banks may report Zelle-received payments as part of broader bank reporting. The IRS has generally noted that Zelle transfers may still be taxable income if they represent compensation."},
  {q:"Which platform earns revenue through a social feed that drives engagement and network effects?", options:["Zelle","PayPal","Venmo","All three"], answer:2, explanation:"Venmo's social feed is its unique engagement mechanism. By making payments social, Venmo drives viral adoption and daily app opens. This engagement supports its revenue streams (instant transfer fees, debit card interchange, business profile fees) by keeping users active."},
  {q:"A landlord wants to collect rent from 20 tenants monthly. Which platform is most appropriate?", options:["Venmo — largest user base","Zelle — bank-to-bank, free, irrevocable","PayPal Goods & Services — offers payment tracking","All three are equally appropriate"], answer:1, explanation:"Zelle is commonly used for rent collection — it's free, bank-to-bank, reaches 2,200+ bank apps, and is irrevocable (once received, tenant can't reverse). The irrevocability, while a consumer risk in fraud scenarios, is actually beneficial for landlords who don't want chargebacks on rent payments."},
  {q:"What is the primary reason Venmo is predominantly used by younger (millennial / Gen Z) demographics?", options:["Venmo has the lowest fees of any payment app","Venmo offers the highest transaction limits","The social feed makes payments a shared social experience that aligns with social media behavior patterns","Venmo is the only app accepted at major retail stores"], answer:2, explanation:"Venmo's social feed resonates with demographics accustomed to sharing life events on social media. Seeing friends' Venmo activity (even without amounts) creates FOMO and social pressure to join the platform. This was the key viral growth mechanism that drove massive adoption among college students."},
  {q:"Which company acquired Venmo as part of a larger acquisition, and for how much?", options:["PayPal acquired Venmo directly for $26 million","PayPal acquired Braintree for $800 million, which included Venmo","eBay acquired Venmo for $1.5 billion","Google acquired Venmo for $500 million"], answer:1, explanation:"PayPal acquired Braintree for $800 million in 2013. Venmo was a Braintree property (Braintree had bought it for $26.2 million in 2012). The $26 million Venmo acquisition — multiplied through Braintree's $800 million sale — represents one of the best investment returns in fintech history."},
  {q:"Which platform's back-end settlement mechanism involves ACH as the actual money movement rail?", options:["PayPal only","Venmo only","Zelle only","Both Zelle and Venmo/PayPal use ACH for bank withdrawals"], answer:3, explanation:"Both Zelle and PayPal/Venmo use ACH. Zelle's bank-to-bank settlement is ACH in the background. PayPal/Venmo use ACH to fund wallets from bank accounts and for standard (non-instant) balance withdrawals. The difference is Zelle has no wallet step — everything is ACH-settled between banks."},
  {q:"If a consumer receives $5,000 in Venmo payments for freelance services in one year, what IRS reporting action does Venmo take?", options:["No reporting — Venmo doesn't report individual transactions","Venmo reports the payments to the IRS via Form 1099-K since the amount exceeds $600","Venmo automatically withholds 28% tax backup withholding","Venmo reports to the state tax authority but not the IRS"], answer:1, explanation:"Because the $5,000 was received as Goods & Services payments (freelance services = commercial), and the total exceeds $600, Venmo/PayPal is required to issue a Form 1099-K to both the freelancer and the IRS. The freelancer must report this income on their tax return."},
  {q:"Which of the following correctly describes the maximum weekly P2P sending limit on Venmo for verified users?", options:["$999","$1,999","$4,999.99","$19,999.99"], answer:2, explanation:"Verified Venmo users (who have provided SSN and personal information for identity verification) have a weekly P2P sending limit of $4,999.99. Unverified users have a $299.99 weekly limit. Identity verification is required to unlock higher limits."},
  {q:"The key similarity between PayPal and Venmo is:", options:["Both are owned by different parent companies","Both operate as digital wallets on PayPal's platform with internal ledger systems","Both are bank-to-bank networks with no stored value","Both are international payment platforms"], answer:1, explanation:"Both PayPal and Venmo are digital wallets operating on PayPal's ledger infrastructure. Internal transfers between users of either platform are ledger entries — no external settlement needed. The brands differ in positioning (PayPal: global commerce; Venmo: social P2P) but share the same underlying wallet technology."},
  {q:"For a small business accepting payments from customers, which option provides the most merchant-grade features (invoicing, dispute protection, analytics)?", options:["Zelle for Business","Venmo Business Profile","PayPal Business Account","All are equivalent"], answer:2, explanation:"PayPal Business Account offers the most comprehensive merchant features: invoice creation, dispute management, Seller Protection, payment links, API integration, multi-currency support, and business analytics. Venmo Business Profile is more limited (US-only, no international, basic analytics). Zelle for Business lacks all these features."}
];
